### ISSUE TITLE
'Shop' CMS Menu section

### ISSUE THREAD

**Issue by jedateach** [silvershop/silvershop-core#122]
I see that the Files section of the SS3 CMS has sub-sections. If we can group admin sections below a 'Shop' menu item, I think this will be a big win for tidiness & usability.

Eg:

 * Pages
 * Shop
  * Orders
  * Products
  * Shipping
  * Zones
  * Settings
 * Reports
 * ...

**Comment by markguinn** [comment]
Just a note for whoever gets around to implementing this. That module has been taken over by Silverstripe Australia - https://github.com/silverstripe-australia/silverstripe-grouped-cms-menu.

**Comment by bummzack** [comment]
I don't think this has to be in core? Whoever wants this can use the grouped-cms-menu module?
