### ISSUE TITLE
Generate sequential order numbers when orders are placed

### ISSUE THREAD

**Issue by jedateach** [silvershop/silvershop-core#144]
The system will currently use the order ID as the order number. This can be confusing for store owners, as it gives the appearance that there are many orders being placed, but not showing up in the back-end. It is actually many orders that are being started, as the order ID is automatically created every time a cart is started.

A better default solution would be to generate a new order reference number when an order is placed.

**Comment by markguinn** [comment]
We could use a strategy pattern for this - so the default would be what you describe above but you could configure the infector to use a different strategy - for example a random string of numbers and letters or adding a prefix. In my experience this is the kind of thing some store owners are pretty specific about so such an approach would allow almost unlimited customisation.

**Comment by jedateach** [comment]
:+1: sounds good to me

**Comment by bummzack** [comment]
Is this still an issue? This should already be doable with the `generateReference` hook?

**Comment by bummzack** [comment]
Closing this. Please reopen if there's still a need for this (eg. something that can't be solved via `generateReference`).
