### ISSUE TITLE
Wrap order state modifications in database transactions

### ISSUE THREAD

**Issue by chillu** [silvershop/silvershop-core#198]
For example, `Order->calculate()` will produce an inconsistent order if it fails halfway through. Jeremy, you'll know best where those transaction capabilities need to be added. Its an important factor to stabilize the module for the project we're working on.

/cc @halkyon @wilr

**Comment by bummzack** [comment]
Closed via #506

**Comment by chillu** [comment]
Nice work Roman, thank you!
