### ISSUE TITLE
Should not be able to add product to cart when variations exist

### ISSUE THREAD

**Issue by nimeso** [silvershop/silvershop-core#231]
On a ProductCatagory I can add a product with Variations to my cart WITHOUT choosing the variation.... I can even get to the checkout. The shop owner will get the order but not know what to send?

![variation_weirdness_03](https://f.cloud.github.com/assets/1796069/2176051/b7326c6e-95ca-11e3-854f-74b31437c9ea.png)

**Comment by bummzack** [comment]
Closed via #516
