### ISSUE TITLE
Page->index() breaks stepped checkout

### ISSUE THREAD

**Issue by jedateach** [silvershop/silvershop-core#261]
index() function on SteppedCheckout gets overidden by Page_Controller index function.

A possible solution is to automatically redirect to the first step in the checkout steps. However, I've noticed in `onAfterInit` that an automatic redirect kicks in if cart is empty. This would cause an infinite loop.

Another solution could be to somehow introduce `index()` on `CheckoutPage_Controller`

**Comment by bummzack** [comment]
Is this still an issue? What exactly is the bug?

**Comment by bummzack** [comment]
Closing this, as it's not clear what the issue is. Feel free to reopen if needed.
