### ISSUE TITLE
Multi-currency support

### ISSUE THREAD

**Issue by jedateach** [silvershop/silvershop-core#29]
In the interest of making the shop module more global, it should allow users to view prices in their local currency.

Here is an implementation proposal:
https://groups.google.com/d/topic/silverstripe-ecommerce/vnFVYy54HwU/discussion

Use cases:
- single currency site
- a few currencies / countries
- many/every currency and country

Provide an interface for manual entry and adjustments.
## Sources

Provide ways to get rates from various sources. Perhaps just abstract CurrencyAgregator class.

**Comment by jedateach** [comment]
This may be useful: https://github.com/swipestripe/silverstripe-swipestripe-currency

**Comment by mediabeastnz** [comment]
Has this been built for this module yet? If not is there a quick way to get multi currency working? I used this module without actually checking if it had multi-currency :(

**Comment by markguinn** [comment]
What's your use case? You can use any currency as your base currency (see the configuration options in the ShopCurrency class), but I don't know of any way to allow the user to select which currency they want to use or browse in one currency and pay in another. I could be wrong though and @jedateach might know of something I don't.

It probably wouldn't be a huge amount of work get a basic implementation of this going though. I'd be happy to help you work out the architecture and/or work with you to get any required core changes pushed through. I bet you can do it easily with a module, though. Something like:

1. Store an exchange rate (relative to the base currency) and an active/inactive flag for each currency.
2. Add an extension to Product and ProductVariation which uses updateSellingPrice to apply the exchange rate.
3. Override the display of prices to use the correct currency formatting (this would be the bit that may require core changes but I haven't yet investigated it).
4. In the long term you'd need a build task to update the exchange rates from some external source. A quick and dirty implementation would not require this though if you just had a modeladmin for the various currencies.
5. Implement some frontend code for a price dropdown and a controller to receive that action.

If you don't have the time or expertise to implement the above (or your own version of it) you could also try creating a bounty.

**Comment by mediabeastnz** [comment]
Yeah my use case is the user needs to be able to select a currency (possibly auto detect) and products will then show a price at that currency.

I was thinking just set a session for the selected currency? and based on that override the display of all prices.

I might have a go at setting a simple module up and getting some feedback?

Appreciate the help!

**Comment by markguinn** [comment]
I think that's exactly the right approach. Let me know here or on gitter if you get stuck.

**Comment by mediabeastnz** [comment]
I quickly began putting some raw/untested code together this evening. https://github.com/mediabeastnz/silverstripe-shop-currency

I was doing some research on other e-commerce sites and quite a few of them just display the base price e.g. NZD $10.00 and then if you change your currency to USD it just adds a bit of text under the base price e.g. Approx. USD $6.50

Is this a good approach? As obviously if we show just $6.50 the user will be shocked when it comes to checking out and they see the NZD price for example.

This just means implementing this module would require and update to a few templates (product, product listing, emails, checkout table, payment confirmation).

Keen to get more feedback on this (and my code).

**Comment by markguinn** [comment]
Ah, you've revealed a flaw in my original plan for sure. If we change the sellingPrice, we would need to also change all the order modifiers as shipping or tax might still be in the base currency.

Initial thoughts: I like your alternate approach of keeping all calculations in the base currency, and essentially making a secondary price available for the selected currency. Each site would actually then have the option of displaying only the selected currency or both the base currency and the selected as you mention above. It would all be in the templates and therefore easily overridden.

I think the catch here is that you'll need to add extensions to:

1. Product
2. ProductVariation
3. OrderAttribute (possibly OrderItem and OrderModifier separately, I'm not sure)
4. Order (to give an alternate SubTotal, Total, and AmountPaid)

Another aspect of this to think through is whether you need to charge in the selected currency or in the base currency. If the former, we'll also need to look at adding an extension hook to OrderProcessor::createPayment (line 129). If the latter nothing needs to be done.

Finally, one bit of feedback about your code is that your extensions probably need to either be named more specifically (i.e. MultiCurrentProductExtension or HasMultipleCurrencies) so they don't class with other modules.

**Comment by mediabeastnz** [comment]
My use case would only ever charge in NZD (base currency) so i wasn't going to build this in for now, i might just add this to the todo list.

Appreciate the feedback, i'll continue to develop this over the next week and hopefully have something solid done soon. I'll update my class names to be more specific :)

I'll keep posting here as well if i have any architecture questions etc!

**Comment by anselmdk** [comment]
A fast comment: To make this true multi currency, we'd need to be able to completely remove the dollar symbol. While I guess `USD $6.50` is just fine, this could like like this in Euro: `EUR 5,-`.

**Comment by markguinn** [comment]
Thanks for the feedback, @anselmdk. 
@mediabeastnz did you end up using your rough code in a production site?

**Comment by bummzack** [comment]
Closing in favor of #621
