### ISSUE TITLE
Money values can't seem to go over $10 mil

### ISSUE THREAD

**Issue by jedateach** [silvershop/silvershop-core#292]
Either allow greater values, or prevent going over.

![screen shot 2014-11-05 at 2 38 10 pm](https://cloud.githubusercontent.com/assets/1356335/4911587/1f15b018-6490-11e4-8faa-12d9a62d47e6.png)

**Comment by riddler7** [comment]
Money fields would be ok, they are Decimal(19,4).

The default for Currency is 9,2, leaving only 7 digits to the left of the decimal point.

Maybe change UnitPrice and any other fields to Currency(19,4)
