### ISSUE TITLE
CheckoutStep_ContactDetails skip feature

### ISSUE THREAD

**Issue by jedateach** [silvershop/silvershop-core#328]
The CheckoutStep_ContactDetails skip feature I introduced in ca6f7b9d34c3d467cd8ec813dd5da48f286ea191 is still broken.
If there is missing information, the validation failed message will show up...even when it is the first time the user is looking at the data. It is happening due to the use of the `->validate()` call.

Luckily this feature is only enabled with the following config:
```
CheckoutStep_ContactDetails:
  skip_if_logged_in: true
```

**Comment by bummzack** [comment]
Closed via #518
