### ISSUE TITLE
Shopping cart hooks/API improvement

### ISSUE THREAD

**Issue by jedateach** [silvershop/silvershop-core#334]
I think we need to improve the API / hooks of the shopping cart to make it more extensible.

I've been working on on a submodule to allow defining minimum item quantities. My intention is to do this using the ShoppingCart hooks, and allow/deny modifications based on per-product minimum quantity settings.

I've now found this won't be as easy as I thought.

To cover this use case, the placement of extension hooks will need to be updated to cause an action to not continue, should the quantity be set to 0 for example.

The ShoppingCart class has been intended to be a gateway to updating the cart Items DataList, but this issue makes it evident to me that it isn't quite succeeding.
My recent `CartForm` addition to SS updates item quantities by directly writing the item. This means that any hooks are being avoided, which kind of defeats having hooks at all. Another area to look at.

A major caveat to consider is the fact that multiple extensions pointing to the same hook could cause some unpredictable behaviour, as the extension execution order isn't entirely clear. (Is this where the need for an event system in SS arises?)

**Comment by jedateach** [comment]
@markguinn Hopefully I've explained this clearly. Please let me know if anything needs clarification.
I think you did some of the hook additions. Do you have any thoughts on this?

**Comment by markguinn** [comment]
That's a gnarly one for sure. The only work I've done so far on the cart is adding the response hooks for ajax. Those don't have any ability to affect the actual transaction, just reformat the response.

I could be missing the point entirely but if not it seems like there are a few options here.

1. Direct everything through the ShoppingCart as is. That would mean refactoring your CartForm changes to use ShoppingCart as well. If we add a beforeAdd/Remove/UpdateItem extension hook or a canAdd/Remove/UpdateItem method with an extension hook that would allow us to prevent the transaction from taking place. I'd suggest maybe adding an afterAdd/Remove/UpdateItem hook in addition to the updateXXXResponse hooks in place for the ajax.
2. Refactor ShoppingCart to be a subclass of Order so the Items collection could be directly manipulated. I haven't thought through the details of this but I imagine it would mean extensions would need to also hook into OrderItem for onBeforeWrite etc making them more complicated. It would also probably lean towards a major version bump.

All in all, my preference would be the former.

Regarding multiple extensions, we could investigate wrapping the whole add/remove/update action in a DB transaction which might mitigate any effects of multiple extensions being in play (i.e. if one extension cancels the transaction any changes from the previous ones could be rolled back).

**Comment by riddler7** [comment]
Would it make sense to also turn the ShoppingCart class into a service (can be replaced with the injector) and use the config system.

It's very hard to modify ShoppingCart. For a current project I wanted to be able to modify the session id, as we are running multiple "Stores" and want to have a separate cart for each store.

**Comment by bummzack** [comment]
I don't see anything wrong with making ShoppingCart a subclass of `Object`. That would enable `create` syntax and Injector overrides as well as the possibility to add extension hooks on the cart itself. Do you want to PR?

**Comment by wilr** [comment]
Old issue but `ShoppingCart` now uses `Injectable` so in theory can be replaced giving this card some option. More specific changes could be looked at on new issues.
