### ISSUE TITLE
New Product on Catalog not working

### ISSUE THREAD

**Issue by redor303** [silvershop/silvershop-core#388]
Add Product Button on Catalog menu doesn't seem to work on Silverstripe 3.2.
Reported Error is:
[User Error] Uncaught SS_DatabaseException: Couldn't run query: SELECT DISTINCT "SiteTree"."ClassName", "SiteTree"."LastEdited", "SiteTree"."Created", "SiteTree"."URLSegment", "SiteTree"."Title", "SiteTree"."MenuTitle", "SiteTree"."Content", "SiteTree"."MetaDescription", "SiteTree"."ExtraMeta", "SiteTree"."ShowInMenus", "SiteTree"."ShowInSearch", "SiteTree"."Sort", "SiteTree"."HasBrokenFile", "SiteTree"."HasBrokenLink", "SiteTree"."ReportClass", "SiteTree"."CanViewType", "SiteTree"."CanEditType", "SiteTree"."Version", "SiteTree"."ParentID", "SiteTree"."ID", CASE WHEN "SiteTree"."ClassName" IS NOT NULL THEN "SiteTree"."ClassName" ELSE 'SiteTree' END AS "RecordClassName" FROM "SiteTree" WHERE ("SiteTree"."ID" NOT IN ()) AND ("SiteTree"."ClassName" IN (?)) ORDER BY "SiteTree"."Sort" ASC You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')) AND ("SiteTree"."ClassName" IN (?)) ORDER BY "SiteTree"."Sort" ASC' at line 5
GET /admin/catalog/Product/EditForm/field/Product/item/new?isDev=1&isDevtoken=a67ba5ba7bc0621f9e3a601183bb20b8

**Comment by bbowden** [comment]
I have noticed this error. A related? error occurs when creating a new product page that is not a child of a category. Neither is a showstopper.

**Comment by bummzack** [comment]
What version of shop is this? I tried with 1.3, the current master branch and 2.0 and the problem didn't show up… Maybe it's related to some custom code or another module?

**Comment by bbowden** [comment]
Since this was posted, I have launched two shop sites. Creating products not in categories is not a problem. I vote closing the issue.

**Comment by bummzack** [comment]
Closing this, as it seems to be resolved. @redor303 feel free to reopen if the problem persists on your side.
