### ISSUE TITLE
Prevent incorrect shipping weights

### ISSUE THREAD

**Issue by jedateach** [silvershop/silvershop-core#39]
Sometimes the wrong weight can be entered, resulting in bad shipping cost calculation.

A report showing weights that are strange eg 500kg for a $25 product would be useful.

Also providing an input field that allows choosing the units (eg grams, kg etc) could help. https://gist.github.com/2503707

Convert base unit to grams, rather than kilograms.

Allowing for ounces might help also.

**Comment by wilr** [comment]
Closing as not part of core.
