### ISSUE TITLE
Purpose of ShopQuantityField

### ISSUE THREAD

**Issue by adrian-stein** [silvershop/silvershop-core#394]
What is the purpose of the ShopQuantityField class. The CartForm does not use it to render by default as it's construct method creates CartEditField objects which render as NumericFields. I like the idea of how it has the option to be able to increase and decrease the quantity of a product by 1 but how can it be implemented?  I cant find anything obvious or way to bring it into play?

**Comment by adrian-stein** [comment]
@markguinn Dont suppose you know?

**Comment by markguinn** [comment]
That was before my time I'm afraid. I think CartForm used to use it. I've implemented a similar thing just using ajaxified links (just using the same cart add and remove links used on the product pages) for the + and - buttons.

**Comment by wilr** [comment]
Looks like the field is rendered on `Cart.ss`. Field sounds like it would encapsulate a good set to operations (validation etc) so keeping it and should probably look to make sure it is used consistently in the next version.
