### ISSUE TITLE
Cannot enable variations

### ISSUE THREAD

**Issue by Lazarus404** [silvershop/silvershop-core#400]
I see a variations tab, and can add items here, but when saving a variation, the item always says "You can choose variation attributes after saving for the first time, if they exist."  Saving doesn't allow for attributes to be added.  It simply doesn't appear that variations has been properly enabled.  Please advise how to do this.

Thanks

**Comment by markguinn** [comment]
You have to set up some attribute types (e.g. Color, Size, etc) under Catalog > Attributes first, then you need to enable on or more of those attributes to the product you're creating, THEN you'll be able to set them up for a particular variation.

**Comment by bummzack** [comment]
Updated the user documentation. It can be found here: https://github.com/silvershop/silvershop-core/blob/2.0/docs_user/en/ProductVariations.md
