### ISSUE TITLE
Use inline CSS styles for Emails

### ISSUE THREAD

**Issue by bummzack** [silvershop/silvershop-core#414]
Something like [emogrifier](https://github.com/jjriv/emogrifier) should be used to inline order CSS instead of adding the styles in a `<style>` tag. Ensures better compatibility with Email clients (especially Outlook).

**Comment by markguinn** [comment]
I've got a module for this: https://github.com/markguinn/silverstripe-email-helpers

Do you think it's worth integrating it out of the box? I suppose as long as do it in such a way that it can be disabled with the injector it makes sense.

**Comment by bummzack** [comment]
Oh, I wasn't aware of this module.
I think styles should be inlined by default. In an ideal world, there would just be a CSS file that's getting inlined instead of the inclusion of styles via SilverStripe template.

Personally, I'd probably opt for using that module as a default for shop 2.0 and maybe clean up the templates a bit. Currently the Email template loads an external CSS *and* has styles in a `<style>` tag.

Does the module also allow inline images and other assets (base64 encoding)?

**Comment by markguinn** [comment]
The module is really just a wrapper for Emogrifier. At the time I wrote it there wasn't support for that but Emogrifier may have evolved since then.

**Comment by markguinn** [comment]
There's also this, which I haven't yet looked into: http://foundation.zurb.com/emails/email-templates.html

I don't think it's tied to the full Foundation framework. I wonder if we could base the new email templates on their templates and base CSS?

**Comment by bummzack** [comment]
AFAIK emogrifier doesn't support inlining of images.
I think it's a good idea to look at these templates, or the mailchimp blueprints: https://github.com/mailchimp/Email-Blueprints

Maybe the ones you linked to could serve as a base for our own templates, but in the end it's just table-based layouts.

Regarding integrating your module into shop: If shop would use `Email::create` instead of `new Email`, it should be possible to just use `StyledHtmlEmail` with an Injector override, right?

**Comment by markguinn** [comment]
That's what I was thinking, yeah.

**Comment by bummzack** [comment]
What about the following procedure:
 - Where appropriate, update `new Class` with `Class::create` in the *develop* branch, so that users can already easily integrate your module.
 - At a later stage (2.0), rework Email templates and styles. Maybe even default to your module/emogrifier?

**Comment by markguinn** [comment]
I think that's a great plan. And if we can find anything that does image inlining that'd be neat too.

**Comment by markguinn** [comment]
It doesn't matter to me if we end up basing our templates on Foundation or Mailchimp. I think that call can be made by whoever ends up doing the work.

**Comment by jordanmkoncz** [comment]
Has anyone successfully used `silverstripe-email-helpers` or any other solution with `silvershop-core 1.2.x` to get CSS styles inlined for all the shop emails? I'm trying to avoid having to fork `silvership-core` just to get inlined CSS for the shop emails.

**Comment by bummzack** [comment]
This approach should work:

Install the [silverstripe-email-helpers](https://github.com/markguinn/silverstripe-email-helpers) module, then add the following to your config file:
```yaml
Injector:
  Email:
    class: StyledHtmlEmail
```
After `dev/build` all emails should run through emogrifier…
Styles still need to be in a `<style>` block in your template though. 
Don't use HTML comments (`<!-- -->`) in there, as these will prevent that styles are being inlined.

**Comment by bummzack** [comment]
With 2.0, this is going to be enabled by default, so for me, it's not the highest priority to add it to the documentation. I'd gladly merge a PR if you want to improve the docs in this regard.

**Comment by wilr** [comment]
Enabled by default now. Documentation exists to redefine the class.
