### ISSUE TITLE
SS 3.3 RC2 breaks variations

### ISSUE THREAD

**Issue by bbowden** [silvershop/silvershop-core#427]
Using SS-Shop 1.2 with SS 3.3 RC2 and I can choose an attribute but trying to Add Variation gives an error:
Error at line 55 of /Users/macbookbruce/websites/felters/framework/model/connect/DBConnector.php
Reverting back to SS 3.2 and the error goes away.

cheers
bruce

**Comment by markguinn** [comment]
Thanks for reporting this. I've seen similar issues with SS 3.3 and I'm not sure what's causing that. If you find out let me know! If not, know that it's on my radar so it'll hopefully be fixed shortly.

**Comment by markguinn** [comment]
@bbowden are you using https://github.com/silverstripe-labs/silverstripe-fulltextsearch on this site? If so you should update to a newer version (~2.1.1). If not we can debug from there.

**Comment by bbowden** [comment]
Hi Mark,
I’m not using that module.  The site is unusual in that SS-Shop has become a booking tool rather than a selling tool but all changes are done outside the shop module code. My development site is on my Mac so, with luck, that may make the debugging a little easier.

cheers
Bruce

**Comment by markguinn** [comment]
Are you using any other module that might wrap the database connector? For example, pre-1.0 versions of my clockwork module?

**Comment by bummzack** [comment]
I've just encountered this issue as well. It seems to look for a `ProductVariation_Live` table, but that doesn't exist.
I suspect this is related to the changes to `Versioned` that were [introduced with 3.3](https://docs.silverstripe.org/en/3.3/changelogs/3.3.0/). 

To me it looks like this declaration: `Versioned('Live')` didn't previously require a `_Live` table, since the only version was `Live`, but with 3.3 this seems to be the case (although dev/build doesn't create them, so this might be a framework bug).

Using the `Versioned` extension for just one "Stage" seems questionable to me anyways… why is `ProductVariation` versioned with just `Live`? Instead of `Stage` and `Live`?

**Comment by bummzack** [comment]
This is definitely a framework issue. I'll open an issue over there and reference it back here.

**Comment by markguinn** [comment]
I think the idea was that we wouldn't need to deal with publishing changes, but we'd still have a record so, for example, historical orders would display the correct data from when the item was purchased. It's been nothing but trouble for me though.

**Comment by markguinn** [comment]
Once 4.0 drops it should be much easier to just make this versioned with Stage/Live I think.

**Comment by bummzack** [comment]
Yeah, I understand the original idea behind it. If implemented properly, this should work, right? We don't actually need stages for the ProductVariation, but much rather a Version-History…

**Comment by markguinn** [comment]
Yes in general it does work. Any problems I've had with it seem to have gone away (up to this) but I had always solved it by creating views of this table with the _Live and _Stage suffixes.

**Comment by bummzack** [comment]
It seems to me, that `ProductVariation_Live` never existed, since there's only one stage… which then defaults to the base-name. This seems to cause an issue with 3.3 however. I've found the surce of the problem though. Writing an issue as we speak ;)

**Comment by markguinn** [comment]
Your analysis is correct. I'm remembering now that the issue I faced was with Uncle Cheese's better buttons module making assumptions about a _Live table existing and he had fixed those issues. It appears that framework has now introduced a similar bug. An easy workaround in the meantime is to create views of `SELECT * FROM ProductVariation` at ProductVariation_Live and ProductVariation_Stage.

**Comment by bummzack** [comment]
Here it is: https://github.com/silverstripe/silverstripe-framework/issues/5189

**Comment by bummzack** [comment]
Fixed in SilverStripe 3.3.2
