### ISSUE TITLE
Rename branches to be in line with silverstripe framework

### ISSUE THREAD

**Issue by bummzack** [silvershop/silvershop-core#428]
Mark and I were discussing about renaming branches and where future versions should be developed.
Currently we have:

- `master` → 1.x development branch
- `2.0` → 2.x development branch
- `1.0` → old 1.0 version
- `0.9` → Version compatible with SilverStripe 2.4

I think `develop-2.0` has become obsolete? I don't know about the other branches…

SilverStripe (framework) seems to use `master` for the most up to date version, so that would (currently) be `4.x`. Development on 3.x goes into `3`, minor versions go into `3.1`, `3.2`, `3.3` etc. for patch level releases.

If we were to adopt this pattern, our branches would look like this:

- `master` → 2.x development branch
- `1` → 1.x development branch
- `1.0` → 1.0 development (probably not gonna happen)
- `0.9` → 0.9 development (probably not gonna happen)

If needed, we can also create branches for `1.1`, `1.2` etc. and work on patch level releases, such as `1.2.x`. At the moment tags seem to be sufficient for this though.

Thoughts?

**Comment by markguinn** [comment]
My current preference would be to leave things as they are until 2.0 becomes the main development target (maybe over the summer some time?). Right now, I'd prefer to have most pull requests go into the next 1.x release unless they represent breaking changes. I could be easily persuaded otherwise though.

**Comment by wilr** [comment]
@bummzack Has this been tidied up enough? At this stage I think focusing on 2.X and ongoing rather than 1.2.x would be most practical.

**Comment by bummzack** [comment]
@wilr Yeah, master is currently meant for 2.x development and there's a `1` branch for further development that should go into `1.x`. As soon as we start on features for `3.x` we can branch current master into `2` for `2.x` and use master for `3.x`… 

master should always be the future development branch.
