### ISSUE TITLE
.git directory is missing

### ISSUE THREAD

**Issue by bbowden** [silvershop/silvershop-core#442]
Trying to update a site from shop 1.1 to 1.2 via composer but I get the following message:
[RuntimeException]                                                                                      
  The .git directory is missing from shop/, see https://getcomposer.org/commit-deps for more information

**Comment by markguinn** [comment]
I'd suggest just deleting the shop folder and running `composer update`.

**Comment by bbowden** [comment]
That fixed it, thanks

cheers
bruce
