### ISSUE TITLE
canPurchase decorator methods not working

### ISSUE THREAD

**Issue by fonsekaean** [silvershop/silvershop-core#443]
The canPurchaser decorator methods doesnt work on the Product and ProductVariation, as it is calling extendedCan and the canPurchaser decorator function doesnt get the quantity. 

Updating the code in Product->canPurchase method from 

```
// Standard mechanism for accepting permission changes from decorators
        $extended = $this->extendedCan('canPurchase', $member, $quantity);
        if ($allowpurchase && $extended !== null) {
            $allowpurchase = $extended;
        }
```

to 

```
// Standard mechanism for accepting permission changes from decorators
        $extended = $this->extend('canPurchase', $member, $quantity);
		if ($allowpurchase && $extended !== null) {
            $allowpurchase = $extended[0];
        }
```

And doing the same on product variation solves the issue. 

Thanks

**Comment by bummzack** [comment]
I've used `canPurchase` in extensions before and it works. I guess the main issue here is, that the `$quantity` parameter is being discarded? So can-purchase checks that involve quantity will fail…

Since `extend`, as well as `extendedCan` filter out `null` values, I guess the code could be rewritten as follows:

```php
$permissions = $this->extend('canPurchase', $member, $quantity);
$permissions[] = $allowpurchase;
return min($permissions);
```
I'll create a PR with that change, if that fixes your issue.

**Comment by bummzack** [comment]
There seem to be other inconsistencies with the `canPurchase` permission checks. The documentation in the `Buyable` interface states that a `ShopBuyableException` should be thrown when the product can't be purchased. That seems to be against the philosophy of permission checks… I guess it was once used to provide some feedback to the user (via Exception message), but I can't find any reference in the code where this is actually being used (`ShopBuyableException` isn't even being thrown anywhere).

I suggest to fix the bug with missing quantity in `1.x` and remove/deprecate `ShopBuyableException` for `2.x`. @markguinn Thoughts?

**Comment by fonsekaean** [comment]
Hello @bummzack, The issue is that the quantity doesnt get passed in to the canPurchase decorator function. I think your code will solve the issue with the canPurchase when the canPurchase decorator has to check for the quantity you are going to purchase. 

Thanks for the fast reply.

**Comment by markguinn** [comment]
Agreed. I think someone went through an exception-happy phase at some point in the past. :) I definitely thing the correct behaviour is to return false rather than throwing an exception. Your suggested approach of fix in 1.0 and deprecate for 2.0 is great.

**Comment by fonsekaean** [comment]
@markguinn I agree too with returning a boolean rather than an exception. If we could return a message somehow to let a user know why the product cannot be purchased will be a +1.

**Comment by markguinn** [comment]
Actually that's [the message] probably the exact reason they originally used an exception.

**Comment by bummzack** [comment]
Yeah, I think so too. 

I searched all of GitHub for `ShopBuyableException` and the only module/implementation that throws this exception seems to be the `shop_stock` module. (it actually throws a subclass, [here](
https://github.com/dnadesign/silverstripe-shop_stock/blob/22eab94dd744e9a46348140af046436302a07954/code/extensions/ProductStockExtension.php#L229)). But even there, there's no message.

Regardless, this whole messaging from within `canPurchase` seems to be wrong. If you implement something like stock-management, `canPurchase` simply returns `false` if you try to purchase more products than there are available. There's really no need to show a message there. 

Messages can be triggered when a user tries to add too many of said Product to cart (eg. somewhere in a Shopping-cart-controller). Then on the Product-Page there should be a message saying: `Only X left in Stock` and the input field could be a Numeric-Stepper with an upper limit of `X`. There are really a lot of ways to implement proper feedback…
If we really need to return reasons/messages from `canPurchase` itself, then I'd suggest a similar pattern like the `ValidationResult` in SilverStripe, which gets passed to all Extensions. Extensions can then add an error to the validation-result, together with an Error-Message that should be displayed in the frontend.

**Comment by warslett** [comment]
@bummzack FYI I am now getting a big ugly errors using the shop_stock module
Fatal error: Class 'ShopBuyableException' not found in /var/www/html/silvershop-stock/code/exceptions/BuyableNotEnoughStockException.php on line 7

**Comment by bummzack** [comment]
@warslett That's because this PR (https://github.com/silvershop/silvershop-stock/pull/7) still needs to be merged… I'll do that right away.

**Comment by warslett** [comment]
@bummzack thank you

**Comment by bummzack** [comment]
@warslett I've tagged a 1.0.3 release of the stock module.
