### ISSUE TITLE
composer install complains about minimum-stability

### ISSUE THREAD

**Issue by wildflower** [silvershop/silvershop-core#448]
I've tried 
composer require "silvershop/silvershop-core:dev-master"
from inside my silverstripe directory i.e (/var/www/myproject)
and get this message:
  [InvalidArgumentException]
  Could not find package silvershop/silvershop-core at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

I've tried with minimum-stability (dev) as well by editing my composer.json file.

I'm guessing this is more an issue with composer or possibly the packagist (or however composer does it) record doesn't have a stability/version flag?

I can git clone the project well enough to get the code on to my local vmware server so the issue is not critical at  all

**Comment by bbowden** [comment]
"burnbright/silverstripe-shop": "dev-master" will work and should point to the same files.

**Comment by markguinn** [comment]
The composer package is `silvershop/core`
