### ISSUE TITLE
Address: no relation back to Order

### ISSUE THREAD

**Issue by wernerkrauss** [silvershop/silvershop-core#475]
As discussed on gitter yesterday i want to note it here:

Order has_one BookingAddress and ShippingAddress to Address.

For a project i needed the reverse order, from an Adress i want to get all Orders where it's used e.g. as shipping Address.

This works:

```
//in Address class:
private static $has_many = [
    'ShippingAddressOrders' => 'Order.ShippingAddress',
    'BillingAddressOrders' => 'Order.BillingAddress'
];

//in my Task:
$latestOrder = $address->ShippingAddressOrders()->sort('Created DESC')->first();

```

I'm happy to create a PR, could you suggest a better naming of the relations?

**Comment by markguinn** [comment]
Thanks Werner. I might go with ShippedOrders and BilledOrders just for brevity, but what you've got is fine too.
