### ISSUE TITLE
Order::onBeforeDelete does not delete relations

### ISSUE THREAD

**Issue by NobrainerWeb** [silvershop/silvershop-core#484]
As far as i can tell the method Order::onBeforeDelete does not delete OrderItems, Modifier and so on.
It does call ```$this->Items()->removeAll(); ``` but the relation is not deleted.

I do this to delete OrderItems
```
foreach ($order->Items() as $item) {
	$item->delete();
}
```
testet on SS 3.2.1

**Comment by bummzack** [comment]
Closed via #508
