### ISSUE TITLE
Remove restriction on shopping cart continue pages

### ISSUE THREAD

**Issue by bbowden** [silvershop/silvershop-core#488]
Currently the 'Continue' page for the shopping cart must be a product category. This is unnecessarily restrictive, especially for sites with no categories or multiple categories.

I suggest this restriction is removed to allow any page to be chosen as the 'Continue shopping' page.

**Comment by bummzack** [comment]
Want to create a PR?

**Comment by bummzack** [comment]
Closed via #507
