### ISSUE TITLE
Changing the project name to silvershop-core has broken an image src url

### ISSUE THREAD

**Issue by wildflower** [silvershop/silvershop-core#502]
On the checkout page, the Cart.ss template is being used.
for the "Remove All" link it references the remove.gif thus:
src="shop/images/remove.gif" alt="x"

I've updated using Composer and the default folder used was silvershop-core

The image should point to img src="/silvershop-core/images/remove.gif" alt="x" or maybe there can be a route setup that points at silvershop-core to catch any other references?

**Comment by bummzack** [comment]
Fixed via #503
