### ISSUE TITLE
How do I set my site to use a different currency?

### ISSUE THREAD

**Issue by Edelfix** [silvershop/silvershop-core#504]
### In the file  silvershop-core/docs/en/01_Getting_Set_Up/03_Troubleshooting.md
i found a bug.
wrong:
---------------------
How do I set my site to use a different currency?
//where 'CUR' is the currency code
Payment::set_site_currency('CUR');
---------------------
rigth:
in mysite\_config\config.yml
---------------
Currency:
  currency_symbol: '€'
---------------
then ?flush=all

**Comment by bummzack** [comment]
Thanks. Can you create a PR for this, please?

**Comment by bummzack** [comment]
Closed via #505
