### ISSUE TITLE
Orde Email r number/Reference problem

### ISSUE THREAD

**Issue by ctx2002** [silvershop/silvershop-core#520]
under lang/en.yml file.

OrderNotifier:
    ADMINNOTIFICATIONSUBJECT: "Order #%d Notification"
    CONFIRMATIONSUBJECT: "Order #%d Confirmation"
    RECEIPTSUBJECT: "Order #%d Receipt"

all of above %d should be changed to %s.
because, not every order number is a number, and Order Reference field can be override to a different format.

I think there are many places been referenced to order ID. and all should change to %s.
otherwise , Order Email subject becomes "Order #0 Receipt".

for example:

there are many place in Shop OrderEmailNotifier.php has this sort of code:

$subject = sprintf(
            _t("OrderNotifier.CONFIRMATIONSUBJECT", "Order #%d Confirmation"),
            $this->order->Reference
        );
$this->order->Reference may or may not be a number.

also, check Order's generateReference funciton, this function allows customized code to override 
Order's Reference field.

**Comment by bummzack** [comment]
This has been changed in 2.0, as we use the proper translation syntax (see https://docs.silverstripe.org/en/3.4/developer_guides/i18n/#the-t-function).

Feel free to create a PR with these changes against the `1` branch though…
