### ISSUE TITLE
New to Silvershop and Silverstripe

### ISSUE THREAD

**Issue by tehnools** [silvershop/silvershop-core#553]
I would like to add a cart to my shop page as well finalizing an order  for a shop.

Did a flush but it's still not appearing. 

`<div class="container" id="shop">

```
$BreadCrumbs

<% include SideBar %>
$Cart
<h1>$Title</h1>
<div class="col-sm-9 col-md-9">
    <div class="container-fluid" id="shop-main">


        <% loop FeaturedProducts  %>
            <div class="col-md-3" >
                <% if $Image %>
                    <a href="$Link">$Image</a>
                <% else %>
                    <a href="$Link"><img src="$ThemeDir/images/placeholder.png" ></a>
                <% end_if %>
                <h3>$Title</h3>
                <p>NZD - $Price.Nice</p>
                <a class="btn btn-danger" href="$Link" role="button">View</a>
                <a class="btn btn-buy" href="$Link" role="button">Buy</a>
            </div><!-- /.col-md-3 -->
        <% end_loop %>
    </div>

    <ul class="pagination pagination-md" id="page-nav">
        <li><a href="#">1</a></li>
        <li><a href="#">2</a></li>
        <li><a href="#">3</a></li>
        <li><a href="#">4</a></li>
        <li><a href="#">5</a></li>
    </ul>
</div>
```

</div>`

**Comment by bummzack** [comment]
Not sure what your issue is. You should use `<% loop $FeaturedProducts %>` and make sure you actually have featured products?

For "getting started" questions, I suggest you look into the documentation or check out our chat: https://gitter.im/silvershop/silvershop-core

**Comment by tehnools** [comment]
Sorry for being unclear. It was the $Image that wasn't showing up in the page

**Comment by tehnools** [comment]
As well as my $Cart

**Comment by wilr** [comment]
@tehnools Can you please use the Forum (https://www.silverstripe.org/community/forums/e-commerce-modules/) or IRC for support questions rather than Github issues. More people available to help with your questions on there.
