### ISSUE TITLE
Receipt emails not being sent when an order has been completed.

### ISSUE THREAD

**Issue by sapiensfio** [silvershop/silvershop-core#562]
In my project, email receipts don't send when I use the 2.1.0 release. I believe this is because an order's Status and Paid properties are set simultaneously meaning that the condition to send an email receipt never evaluates to true (as it checks to see if the Status property is equal to "Paid" and the Paid property is falsey). 

Please refer to my pull request for a solution to this problem (#561)

**Comment by bummzack** [comment]
Fixed via #563 
Will release a 2.1.1 version that includes this fix.
