### ISSUE TITLE
Custom Email notifier

### ISSUE THREAD

**Issue by catharsisjelly** [silvershop/silvershop-core#569]
I can't see currently a way of adding logic to the `OrderEmailNotifier`. Basically my use case is that the user when purchasing an item (a training course) needs to supply email addresses of people that  are attending the course. The e-mail the attendees get may be different from the person purchasing the training course (with dates etc).

The only way I can see to do this is to build a custom `OrderEmailNotifier` and then use that instead of the current one. This way I can control who get's which template and what information is taken out of the relevant Order.

I'm going to put together a little PR to suggest a way to do this but obviously will take guidance from the community.

**Comment by bummzack** [comment]
It really depends *when* you need to notify attendees. It could be sufficient to just use the `onPaid` extension-hook (implemented in an extension added to `Order`) and send the E-Mails from there.

But I agree, the `OrderEmailNotifier` is not very extensible. An architecture that makes it easier to send all kinds of shop-related Emails could be useful, but it might be hard to find a solution that handles most possible use-cases elegantly.

**Comment by catharsisjelly** [comment]
For my scenario you may want the people attending the course to receive an e-mail before the Order is paid for. For instance some companies ay want to pay by invoice (after X days) so in this case the hook into Paid won't work. I could create a new status of course and hook into that instead.

**Comment by bummzack** [comment]
If you just need to be able to use a custom Subclass of `OrderEmailNotifier`, then this is already in place, see my comment on the PR (#570)

**Comment by catharsisjelly** [comment]
Yep a subclass would do it but was not sure how to make the OrderProcessor use my Subclass and not the standard `OrderEmailNotifier`

**Comment by bummzack** [comment]
You can use the Injector, eg. in your config file:

```yml
Injector:
  OrderEmailNotifier:
    class: MyCustomOrderEmailNotifier
```

Then in your `MyCustomOrderEmailNotifier` class, you could implement other methods, such as `sendNotificationToAttendees` etc.

Call these methods from hooks that you added to an extension to `Order`. You can use the `onPaid` and `onPlaceOrder` hooks, or the `onStatusChange` hook if you need to trigger something on status-change.

**Comment by catharsisjelly** [comment]
Thanks @bummzack I'll cancel my PR and/or change the docs :)

**Comment by bummzack** [comment]
You're welcome. Hope it helps to achieve what you're looking for, otherwise feel free to reopen or create a new PR.

As a general rule of thumb in SilverStripe: You can replace pretty much any class via Injector, as long as the `ClassName::create` pattern is being used for instantiation. Caveat: replacements are restricted to a single class, eg. replacing a class doesn't mean that extending classes will then magically inherit from the replaced class.
