### ISSUE TITLE
Cant override product variation title

### ISSUE THREAD

**Issue by adrian-stein** [silvershop/silvershop-core#575]
There is an issue in the ProductVariation class on the method getTitle(). The title cannot be extended unless there is no AttributeValues but I need to update the title  after the default title is created.

Can I suggest instead of ` return implode(self::config()->title_glue, $labelvalues);` use ` $title = implode(self::config()->title_glue, $labelvalues);`

This way the code can exit the if statement and we can extend the title regardless of if one is present or not. Thoughts??

**Comment by bummzack** [comment]
Sounds like a good change. Keen to submit a PR?

**Comment by adrian-stein** [comment]
Done. Fixed by https://github.com/silvershop/silvershop-core/pull/576

**Comment by adrian-stein** [comment]
Take 2. Fixed with https://github.com/silvershop/silvershop-core/pull/577
