### ISSUE TITLE
Deleting Products via the Catalog deletes from Draft Site, but not from published

### ISSUE THREAD

**Issue by beeonlinenz** [silvershop/silvershop-core#579]
To replicate, delete a product via admin/catalog/

The product is deleted from the Catalog (i.e can't be found there), but
1. shows in the SiteTree as 'Removed from Draft', 
2. remains live.

Expected behaviour: Product would also be removed from the Live site.

I assume the Product page also needs
`->deleteFromStage("Live");`

but I'm unsure of how to implement this.

**Comment by bummzack** [comment]
Deleting records doesn't seem to be enabled by default. What did you do to enable deletion of records in the catalog-admin?

**Comment by beeonlinenz** [comment]
Sorry, I mean when you 'edit' a Product from the Catalog - the Delete button there:
e.g.
/admin/catalog/Product/EditForm/field/Product/item/1/edit/
![image](https://cloud.githubusercontent.com/assets/5632715/22948788/a5f895b8-f364-11e6-8d8f-9271d9192ed5.png)

**Comment by bummzack** [comment]
Yeah, somethings seems to be going wrong there… although I get an "Unpublish" button instead of the "Delete" button, and the "Delete" button appears at its place once the product has been unpublished. That seems to be fine, but I get some other PHP errors when trying to unpublish/delete via ModelAdmin.

Not sure if this is a problem with shop, or a bug in handling Versioned records in ModelAdmin.

**Comment by beeonlinenz** [comment]
Thanks Roman, I tracked down my issue to being related to the silvershop-discounts module and the versioned-gridfield.
The baseTable function of the versioned-gridfield was returning 'GiftVoucherProduct' for the ClassName instead of just the Product - which was throwing out the 'published' status.
Overriding that function to just return the ClassName has fixed my problem.

**Comment by asecondwill** [comment]
I've come across this too.  it's confusing users a bit.  

@beeonlinenz  - do you know if the discount module maintainer knows about this?

**Comment by sparkcom** [comment]
@beeonlinenz  and how to rectify the error please?
