### ISSUE TITLE
PriceRange in ProductGroupItem

### ISSUE THREAD

**Issue by rasstislav** [silvershop/silvershop-core#581]
Price in ProductGroupItem (https://github.com/silvershop/silvershop-core/blob/master/templates/Includes/ProductGroupItem.ss#L12) not check PriceRange. This should be same as in Product (https://github.com/silvershop/silvershop-core/blob/master/templates/Layout/Product.ss#L29), or not?

**Comment by bummzack** [comment]
Yes, I think that makes sense. Could you create a PR for this? I guess it would be good to create an include file that can be used in both templates.
