### ISSUE TITLE
WYSIWYG image insertion error undefined method Product_Image

### ISSUE THREAD

**Issue by hp7** [silvershop/silvershop-core#588]
I get this fatal error when trying to insert an image using TinyMCE image button
 **Fatal error: Call to undefined method Product_Image::setSourceQueryParams() in /****/**/framework/model/DataList.php on line 748**

**Using**
		"silverstripe/cms": "3.5.3",
		"silverstripe/framework": "3.5.3",
		"silverstripe/reports": "3.5.3",
		"silverstripe/siteconfig": "3.5.3",
		"silverstripe-themes/simple": "3.1.*",
		"silverstripe/userforms": "dev-master",
		"colymba/gridfield-bulk-editing-tools": "*",
		"silverstripe/secureassets": "dev-master",
		"silverstripe/gridfieldqueuedexport": "dev-master",
		"silverstripe/lumberjack": "1.*@dev",
		"silverstripe-australia/grouped-cms-menu": "dev-master",
		"silverstripe/dms": "dev-master",
		"sheadawson/silverstripe-blocks": "1.1.*",
		"unisolutions/silverstripe-copybutton": "dev-master",
		"micschk/silverstripe-gridfieldsitetreebuttons": "dev-master",
		"micschk/silverstripe-excludechildren": "dev-master",
		"undefinedoffset/silverstripe-nocaptcha": "dev-master",
		"briceburg/silverstripe-pickerfield": "dev-master",
		"taitava/silverstripe-slickcarousel": "dev-master",
		"undefinedoffset/sortablegridfield": "dev-master",
		"silvershop/core": "dev-master"

**Comment by bummzack** [comment]
I'm unable to reproduce your issue.
When does the error show up? After you uploaded/selected an image?

Can you explain the steps that lead to the error? Maybe also post a stacktrace?
`Product_Image` is just a data-extension… but it seems like it assumes it's a DataObject? Do you use `Product_Image` in a relation or something?

**Comment by hp7** [comment]
It happens as soon as the image uploader pop up window is triggered in the CMS of a product category page. 

If you create a product category page and try and add an image in the content area of the category page. It gives me the error

I will try to do a trace when I get back
Thx for the prompt response

**Comment by hp7** [comment]
This is what comes up

Fatal error: Call to undefined method Product_Image::setSourceQueryParams() in /****/****/framework/model/DataList.php on line 748
Call Stack
#	Time	Memory	Function	Location
1	0.0018	280376	{main}( )	.../main.php:0
2	0.1343	13047752	Director::direct( )	.../main.php:191
3	0.1426	13522384	Director::handleRequest( )	.../Director.php:149
4	0.1446	13658080	AdminRootController->handleRequest( )	.../Director.php:385
5	0.1921	19922080	LeftAndMain->handleRequest( )	.../AdminRootController.php:92
6	0.1921	19922624	Controller->handleRequest( )	.../LeftAndMain.php:464
7	0.4213	31167240	RequestHandler->handleRequest( )	.../Controller.php:158
8	0.4298	32258288	RequestHandler->handleRequest( )	.../RequestHandler.php:222
9	0.4865	37190968	RequestHandler->handleRequest( )	.../RequestHandler.php:222
10	0.4872	37200304	RequestHandler->handleAction( )	.../RequestHandler.php:200
11	0.4873	37200968	Form->forTemplate( )	.../RequestHandler.php:288
12	0.4873	37201696	ViewableData->renderWith( )	.../Form.php:1579
13	0.4914	37681568	SSViewer->process( )	.../ViewableData.php:390
14	0.4916	37682936	SSViewer->includeGeneratedTemplate( )	.../SSViewer.php:1226
15	0.4956	38127800	include( '/****/****/silverstripe-cache/****/.cache.framework.templates.Includes.Form.ss' )	.../SSViewer.php:1164
16	0.5716	40285608	XML_val ( )	.../.cache.framework.templates.Includes.Form.ss:63
17	0.5716	40286136	SSViewer_DataPresenter->__call( )	.../.cache.framework.templates.Includes.Form.ss:63
18	0.5716	40286624	SSViewer_Scope->__call( )	.../SSViewer.php:650
19	0.5716	40287112	call_user_func_array:{/****/****/framework/view/SSViewer.php:187} ( )	.../SSViewer.php:187
20	0.5716	40287632	ViewableData->XML_val( )	.../SSViewer.php:187
21	0.5716	40287680	ViewableData->obj( )	.../ViewableData.php:524
22	0.5716	40287776	FormField->FieldHolder( )	.../ViewableData.php:451
23	0.5716	40288480	ViewableData->renderWith( )	.../FormField.php:882
24	0.5717	40289040	SSViewer->process( )	.../ViewableData.php:390
25	0.5719	40290368	SSViewer->includeGeneratedTemplate( )	.../SSViewer.php:1226
26	0.5724	40321952	include( '/****/****/silverstripe-cache/****/.cache.framework.templates.forms.CompositeField_holder.ss' )	.../SSViewer.php:1164
27	0.5733	40332784	XML_val ( )	.../.cache.framework.templates.forms.CompositeField_holder.ss:57
28	0.5733	40333312	SSViewer_DataPresenter->__call( )	.../.cache.framework.templates.forms.CompositeField_holder.ss:57
29	0.5733	40333632	SSViewer_Scope->__call( )	.../SSViewer.php:650
30	0.5733	40334120	call_user_func_array:{/****/****/framework/view/SSViewer.php:187} ( )	.../SSViewer.php:187
31	0.5733	40334704	ViewableData->XML_val( )	.../SSViewer.php:187
32	0.5733	40334752	ViewableData->obj( )	.../ViewableData.php:524
33	0.5733	40335056	TabSet->FieldHolder( )	.../ViewableData.php:451
34	0.5734	40336136	ViewableData->renderWith( )	.../TabSet.php:83
35	0.5735	40336696	SSViewer->process( )	.../ViewableData.php:390
36	0.5737	40337976	SSViewer->includeGeneratedTemplate( )	.../SSViewer.php:1226
37	0.5742	40375264	include( '/****/****/silverstripe-cache/****/.cache.framework.templates.forms.TabSet.ss' )	.../SSViewer.php:1164
38	0.6156	40577368	XML_val ( )	.../.cache.framework.templates.forms.TabSet.ss:69
39	0.6156	40577896	SSViewer_DataPresenter->__call( )	.../.cache.framework.templates.forms.TabSet.ss:69
40	0.6156	40578384	SSViewer_Scope->__call( )	.../SSViewer.php:650
41	0.6156	40578872	call_user_func_array:{/****/****/framework/view/SSViewer.php:187} ( )	.../SSViewer.php:187
42	0.6156	40579392	ViewableData->XML_val( )	.../SSViewer.php:187
43	0.6156	40579440	ViewableData->obj( )	.../ViewableData.php:524
44	0.6156	40579536	FormField->FieldHolder( )	.../ViewableData.php:451
45	0.6157	40580240	ViewableData->renderWith( )	.../FormField.php:882
46	0.6157	40580800	SSViewer->process( )	.../ViewableData.php:390
47	0.6159	40582128	SSViewer->includeGeneratedTemplate( )	.../SSViewer.php:1226
48	0.6164	40613712	include( '/****/****/silverstripe-cache/****/.cache.framework.templates.forms.CompositeField_holder.ss' )	.../SSViewer.php:1164
49	0.6575	40666360	XML_val ( )	.../.cache.framework.templates.forms.CompositeField_holder.ss:47
50	0.6575	40666888	SSViewer_DataPresenter->__call( )	.../.cache.framework.templates.forms.CompositeField_holder.ss:47
51	0.6575	40667208	SSViewer_Scope->__call( )	.../SSViewer.php:650
52	0.6575	40667696	call_user_func_array:{/****/****/framework/view/SSViewer.php:187} ( )	.../SSViewer.php:187
53	0.6575	40668216	ViewableData->XML_val( )	.../SSViewer.php:187
54	0.6575	40668264	ViewableData->obj( )	.../ViewableData.php:524
55	0.6575	40669208	GridField->FieldHolder( )	.../ViewableData.php:451
56	0.7196	41832952	DataList->getIterator( )	.../ViewableData.php:404
57	0.7196	41833416	DataList->toArray( )	.../DataList.php:760
58	0.7260	42011568	DataList->createDataObject( )	.../DataList.php:670

**Comment by hp7** [comment]
Looks like Clean image cache and Regenerating image cache task, has fixed the issue. Very strange, Thanks for the help!
