### ISSUE TITLE
Admin theme display issue

### ISSUE THREAD

**Issue by camexapps** [silvershop/silvershop-core#590]
Hi Guys,

Try to see if this issue had been raised already. Just letting you know I seem to be having issues regarding the vanilla admin theme for SilverStripe 3.5X. This is to do with the Filtering when contracted, hiding some content:

![screen shot 2017-04-07 at 08 57 05](https://cloud.githubusercontent.com/assets/1858524/24775309/5da26152-1b70-11e7-8a68-1e5a19b4514b.png)
![screen shot 2017-04-07 at 08 57 10](https://cloud.githubusercontent.com/assets/1858524/24775310/5ed35ff4-1b70-11e7-8f0d-010d6bc6697b.png)

**Comment by bummzack** [comment]
I don't think this is a vanilla install you have there. Please try to reproduce the issue with just installing SilverStripe CMS/Framework 3.5 and SilverShop 2.x (no additional modules).
