### ISSUE TITLE
Change tax rate

### ISSUE THREAD

**Issue by asecondwill** [silvershop/silvershop-core#595]
How is the tax rate changed for FlatTaxModifier and GlobalTaxModifier?

**Comment by bummzack** [comment]
Rates are being defined via config API.

In the future: could you ask questions like this over in the gitter chat or on slack? These aren't really issues that belong here.

**Comment by asecondwill** [comment]
Is there any documentation as to how though? 

FlatTaxModifier:
  Rate: 0.10

isn't making a change.

**Comment by bummzack** [comment]
https://github.com/silvershop/silvershop-core/blob/master/docs/en/01_Getting_Set_Up/05_Tax.md and https://github.com/silvershop/silvershop-core/blob/master/docs/en/03_How_It_Works/Order_Modifiers.md is all we have atm. Feel free to improve the docs though.
