### ISSUE TITLE
404 when trying to set default shipping address

### ISSUE THREAD

**Issue by asecondwill** [silvershop/silvershop-core#597]
After adding an address to the address book, I clicked "make default shipping" which took me to this address:  /account/setdefaultshipping/15

which gives a 404.

**Comment by bummzack** [comment]
I can't reproduce your issue. Can you be more specific what version of shop you used? Have you tested this on a vanilla installation, without any specific extensions or modules?

**Comment by asecondwill** [comment]
I'm on 2.1.1.  

Ill run more tests including a reinstall today.

**Comment by asecondwill** [comment]
fresh install didn't fix, which made me ponder... oh.  the account page was in the shop folder, not in the root of the pages tree.  not sure i remember doing that, maybe i thought it was tidier.  

Moving it fixes this issue.  sorry to bother.
