### ISSUE TITLE
Default billing address from address book does not populate billing through checkout

### ISSUE THREAD

**Issue by asecondwill** [silvershop/silvershop-core#598]
I'm testing this in a fresh install, no modules.  

Steps:
register an account
add default shipping and billing addresses to my addressbook, 
add a product to cart
checkout
choose "Bill to a different address from this"

Expected:  default billing address populates the fields
Actual:  default shipping (or at least the address used in shipping in previous step) populates the fields.

**Comment by bummzack** [comment]
Are you using single-step checkout? Because by default, the single-step checkout doesn't use the Address-Book-Checkout-Components (`ShippingAddressBookCheckoutComponent` and `BillingAddressBookCheckoutComponent`) which allows you to select existing addresses via Dropdown.

**Comment by asecondwill** [comment]
No. i'm using the stepped checkout:

CheckoutPage:
    steps:
        'membership' : 'CheckoutStep_Membership'
        'contactdetails' : 'CheckoutStep_ContactDetails'
        'shippingaddress' : 'CheckoutStep_Address'
        'billingaddress' : 'CheckoutStep_Address'
        'shippingmethod' : 'CheckoutStep_ShippingMethod'
        'discount' : 'CheckoutStep_Discount'
        'paymentmethod' : 'CheckoutStep_PaymentMethod'
        'summary' : 'CheckoutStep_Summary'

**Comment by asecondwill** [comment]
I have switched to:

````CheckoutStep_AddressBook````

as you suggested in the other ticket.  

And now choosing to use a different address than shipping on the shipping page,  a radio field selection is possible from the address book.  However it doesn't default to the accounts default billing address.

**Comment by asecondwill** [comment]
Just retested this and it is defaulting to the billing default.  thanks again.
