### ISSUE TITLE
CartEditField referencing Product

### ISSUE THREAD

**Issue by catharsisjelly** [silvershop/silvershop-core#605]
Hi all,

I'm extending this and have found a possible bug. `CartEditField` in the `editableItems` function is referencing the `Product` class direct. Should this be using a generic function like `Buyable()`? this would occur if I chose to make something which does not extend `Product` use the `Buyable` interface.

For instance if the the think that I am "buying" is a Ticket for an event.

https://github.com/silvershop/silvershop-core/blob/master/code/cart/CartEditField.php#L99

**Comment by bummzack** [comment]
Yes, definitely use `getBuyable()` instead if that doesn't break stuff. 
Maybe the product form could also be improved to be compatible with custom buyables… but a fix is needed there as well: https://github.com/silvershop/silvershop-core/blob/50977db6854f6a2e285cc6c03a73eb81c5f925aa/code/product/AddProductForm.php#L86

**Comment by catharsisjelly** [comment]
This is now merged so am closing
