### ISSUE TITLE
Prices depending on member group?

### ISSUE THREAD

**Issue by spekulatius** [silvershop/silvershop-core#607]
Hello,

Thank you for this great shop build on my favorite framework/CMS SilverStripe :) I'm new to SilverShop and was wondering if there is an out of the box option/way to make prices depending on the member belonging to a certain group? This should update the prices in the shop and not just at the checkout as well. Any feedback or ideas are appreciated :)

Cheers,
Peter

**Comment by bummzack** [comment]
Hi. You're welcome. I hope you enjoy working with silvershop.
There's a module for your needs, you'll find it here: https://github.com/markguinn/silverstripe-shop-extendedpricing

For future questions, please use the [chat](https://gitter.im/silvershop/silvershop-core) or post your question on stackoverflow.com if it's a question better suited for that format.

**Comment by spekulatius** [comment]
Hello @bummzack 

thank you for the information. I'll ask any further questions in the chat or stackoverflow.

Cheers,
Peter
