### ISSUE TITLE
Rounding errors

### ISSUE THREAD

**Issue by jedateach** [silvershop/silvershop-core#61]
There is the risk that values are incorrect because of rounding or float issues.

A suite of tests would help find these problems.

**Comment by riddler7** [comment]
I've just run into this with the change to Float for Weight etc on Product.

It is fine on PHP 5.6, but on hhvm 0.1 becomes 0.10000000149012, I'm then unable to save the product as it must not exceed 12 characters in length

**Comment by bummzack** [comment]
What prevents you from saving the product? The database should truncate the value, or isn't that the case? Is the DB layer generating an error here?

**Comment by riddler7** [comment]
Finally had a chance to look at it again, the issue is it has setMaxLength(12) on the field, with the rounding issue it is longer than 12 characters.

I've got around the issue by setting them to decimals in the config.

**Comment by bummzack** [comment]
Thanks for the update @riddler7 
So when using decimals, the rounding errors are gone on HHVM? I wonder if we should use decimals instead of floats then?

**Comment by riddler7** [comment]
Yes, changing to decimals fixes the issue.

I believe they were originally decimals, but the problem with decimals is you have to specify the size e.g. Decimal(9,5)

They were changed to floats to be more flexible for different formats e.g. using kg or g

**Comment by bummzack** [comment]
Do we really need to sacrifice stability for that flexibility? I mean, we could have something like `DECIMAL(27,18)` which should be more than enough when it comes to precision. Even `DECIMAL(18,9)` should be fine…

Are there other reasons for the `Floats`? Is it because of RDBMS compatibility? @markguinn do you know?

**Comment by riddler7** [comment]
Decimals would definitely make sense as floats are notoriously unreliable.

Don't think they need to be anything too large, it's not hard to change the field type using the config system or extensions.

**Comment by markguinn** [comment]
I agree (actually just ran into this on a site myself). I'd propose something like `DECIMAL(7,5)` and others can override with config if needed. Any further thoughts on this @riddler7 or @bummzack ?

**Comment by bummzack** [comment]
Sure, let's do it. We don't need to be conservative here IMHO, we can easily go `DECIMAL(12,5)` or even higher. I'd also update the price fields to higher decimal counts to address #292

**Comment by bummzack** [comment]
`DECIMAL(7,5)` is definitely too low, as `99.99999` would be the max value when using the full precision of 5 numbers after the decimal point. I'd vote for something like `DECIMAL(18,6)`. We really don't need to be concerned about memory issues here, where talking about a few bytes per row…

**Comment by markguinn** [comment]
Just pushed a commit with 12,5 for weight / dimensions and 18,4 for prices. Feel free to adjust higher if you want.

**Comment by bummzack** [comment]
Ok, great. Will existing float values automatically convert when the DB field changes the type to DECIMAL? I've actually never tried that.

**Comment by markguinn** [comment]
Yes. `dev/build` handles that just fine.
