### ISSUE TITLE
Developer Documentation Inaccessible

### ISSUE THREAD

**Issue by HARVS1789UK** [silvershop/silvershop-core#612]
The documentation at [http://demo.ss-shop.org/docs](http://demo.ss-shop.org/docs) is currently inaccessible and is redirecting me to an 'account suspended' page.

![Suspended Page](https://user-images.githubusercontent.com/5114645/29030935-8ae18ac0-7b84-11e7-8937-7d2544440981.png)

**Comment by wilr** [comment]
Not using that domain any more as far as I know. Docs are at https://github.com/silvershop/silvershop-core/tree/master/docs/en

**Comment by nimeso** [comment]
Need to update the git readme file

**Comment by wilr** [comment]
Updated
