### ISSUE TITLE
RequireThemedCSS in templates\Layout\Product.ss

### ISSUE THREAD

**Issue by KazBl** [silvershop/silvershop-core#614]
I'm totally new to this module. I was having a sticky beak under the hood when I came across this line:
<% require themedCSS(product,shop) %>

'shop' is supposed to be a module, right? Should it have been 'silvershop' instead? Which 'shop' is it referring to? Is this a module I am supposed to have (but don't)?

**Comment by wilr** [comment]
Hi @KazBl, this is old - it should be updated to silvershop.

**Comment by wilr** [comment]
`themedCSS` call has been removed from v3
