### ISSUE TITLE
Breadcrumb does not respect MenuTitle (Navigation Title)

### ISSUE THREAD

**Issue by zanderwar** [silvershop/silvershop-core#615]
As per title.

In short uses `$Title` instead of `$MenuTitle`

Given that breadcrumbs are for navigation purposes imho it should use `$MenuTitle` aptly named in the CMS "Navigation Label"

**Comment by wilr** [comment]
Tested this on SilverStripe 4 and latest version of shop and MenuTitle is used. $Breadcrumbs is defined on `SiteTree`.
