### ISSUE TITLE
Create a new release

### ISSUE THREAD

**Issue by dhensby** [silvershop/silvershop-core#619]
The last release was 8 months ago and there are bug fixes that would be valuable to make a release now such as the [`beforeUpdateCMSFields` fix](https://github.com/silvershop/silvershop-core/pull/610)

**Comment by bummzack** [comment]
https://github.com/silvershop/silvershop-core/releases/tag/2.3.0

**Comment by bummzack** [comment]
Thanks for the reminder :)

**Comment by dhensby** [comment]
thanks!
