### ISSUE TITLE
Variation input missing at Checkout Page (2.3.0)

### ISSUE THREAD

**Issue by hpeide** [silvershop/silvershop-core#620]
The variation input is missing at the checkout page with the last version:

![screen shot 2017-10-24 at 21 07 11](https://user-images.githubusercontent.com/90961/31963141-03a0b37e-b900-11e7-9bbb-a3433a038772.png)

At v2.2:

![screen shot 2017-10-24 at 21 07 19](https://user-images.githubusercontent.com/90961/31963071-cefdf8c0-b8ff-11e7-91ad-649112392c9d.png)

**Comment by bummzack** [comment]
Thanks for reporting. I'll release a new version with a fix in a sec.

**Comment by bummzack** [comment]
Fixed in 2.3.1 (https://github.com/silvershop/silvershop-core/releases/tag/2.3.1)
