### ISSUE TITLE
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.

### ISSUE THREAD

**Issue by mhenden** [silvershop/silvershop-core#624]
Can one of the team please look at this issue? Thanks!

**Comment by bummzack** [comment]
Just a warning from composer. It'll work regardless.
There's nothing we can do about that until omnipay 3 hits stable…

**Comment by bummzack** [comment]
For reference: https://github.com/thephpleague/omnipay-common/issues/157
