### ISSUE TITLE
Domain of Demo-Shop expired

### ISSUE THREAD

**Issue by witschko** [silvershop/silvershop-core#638]
Hey!

I just stumbled upon the SilverShop module and wanted to checkout the demo store. But it seems that the domain has expired.
Is there another demo or will it be fixed soon? I'd like to have a look at a running instance before testing it for myself.

Thanks
Philipp

![sshop](https://user-images.githubusercontent.com/63436/36298473-9f438eb2-12f8-11e8-95c1-3cbf5043fc41.jpg)

**Comment by wilr** [comment]
@bummzack thoughts? Should we setup a http://demo.silvershop.io/ domain? I am happy to provide hosting for it.

**Comment by bummzack** [comment]
@wilr Sorry, I didn't see this one. Are there any useful up-to-date templates for shop? Otherwise this is going to be bad advertisement 😂 

This is quite low on my priority list to be honest. To get a glimpse of the CMS, one can just set up a new shop and use the populate shop task. To get an impression of the frontend it's probably better to have some sort of showcase?

**Comment by wilr** [comment]
@bummzack Yes to both. I think we should get a page on the site with a showcase if you have any good links but a demo would be useful for us as well..

I've started rewriting the templates to BEM so love to get that work on demo. We've got the shop recipe that would be the basis. 

If someone can setup `demo.silvershop.io` to record `139.162.198.61` I'll play around with the rest

**Comment by bummzack** [comment]
Ok, I think @jelicanin is the man for that. Milan, could you set up the domain name?

**Comment by jelicanin** [comment]
Hi guys,
sry for a late reply, I'm ill last few days...

Subomain `demo.silvershop.io` is pointed.  
Can you check it?

**Comment by wilr** [comment]
Thanks @jelicanin perfect. Will get the recipe up there next couple of days.

**Comment by bummzack** [comment]
@wilr How's your progression on the templates? I think we should make these modifications before releasing, since templates are probably also part of the public api (semver)? What do you think?

@jelicanin Thanks for installing the subdomain and get well soon!

**Comment by wilr** [comment]
When did you want to release? Few templates to update left and then testing so perhaps a week or 2 away..

**Comment by bummzack** [comment]
I don't have a fixed deadline… take your time :)

Although I wanted to do much more, I think it's a good idea to release the module in the current state and not change too much. I'll try to fix some of the open bugs and improve documentation before we release.
