### ISSUE TITLE
Demo is down

### ISSUE THREAD

**Issue by torican** [silvershop/silvershop-core#645]
As per above.

**Comment by wilr** [comment]
Yep on my backlog to action this week. Thanks for the reminder.

**Comment by wilr** [comment]
@JorisDebonnet silverstripe.io is up for me? Should point to github pages.

**Comment by JorisDebonnet** [comment]
Ah, silvershop.io works again now. I guess there was a temporary issue 8 hours ago ...

demo.ss-shop.org also shows something new for me now; not sure what it said before, but now it says "Too many requests". http://ww1.ss-shop.org/ still looks like the domain name was lost though. Perhaps a demo could be put up on demo.silvershop.io instead?

**Comment by wilr** [comment]
@JorisDebonnet yep, got the demo.silvershop.io subdomain setup is something I want to get working but got to finish all the other work first :) If anyone wants to help can provide the SSH login deats for the container

**Comment by wilr** [comment]
Demo is now up, using `silvershop-recipe` and the code is all open source if anyone wants to improve it!
