### ISSUE TITLE
Module should require specific core components, not recipe-cms

### ISSUE THREAD

**Issue by kinglozzer** [silvershop/silvershop-core#671]

**Comment by tzeller** [comment]
is there a workaround since this will be changed - i can't get silvershop installed because of composer error on ss4.2.1:

composer require silvershop/core:^3@dev

brings this error

Problem 1
    - silvershop/core 3.x-dev requires silverstripe/recipe-cms ^1.0.3 -> satisfiable by silverstripe/recipe-cms[1.0.3, 1.0.4, 1.0.x-dev, 1.1.0, 1.1.0-rc1, 1.1.0-rc2, 1.1.1, 1.1.2, 1.1.x-dev, 1.x-dev, 1.2.x-dev] but these conflict with your requirements or minimum-stability.
    - silvershop/core 3.0.0-alpha3 requires silverstripe/recipe-cms ^1.0.3 -> satisfiable by silverstripe/recipe-cms[1.0.3, 1.0.4, 1.0.x-dev, 1.1.0, 1.1.0-rc1, 1.1.0-rc2, 1.1.1, 1.1.2, 1.1.x-dev, 1.x-dev, 1.2.x-dev] but these conflict with your requirements or minimum-stability.
    - silvershop/core 3.0.0-alpha2 requires silverstripe/recipe-cms ^1.0.3 -> satisfiable by silverstripe/recipe-cms[1.0.3, 1.0.4, 1.0.x-dev, 1.1.0, 1.1.0-rc1, 1.1.0-rc2, 1.1.1, 1.1.2, 1.1.x-dev, 1.x-dev, 1.2.x-dev] but these conflict with your requirements or minimum-stability.
    - silvershop/core 3.0.0-alpha1 requires silverstripe/recipe-cms ^1.0.3 -> satisfiable by silverstripe/recipe-cms[1.0.3, 1.0.4, 1.0.x-dev, 1.1.0, 1.1.0-rc1, 1.1.0-rc2, 1.1.1, 1.1.2, 1.1.x-dev, 1.x-dev, 1.2.x-dev] but these conflict with your requirements or minimum-stability.
    - Installation request for silvershop/core ^3@dev -> satisfiable by silvershop/core[3.0.0-alpha1, 3.0.0-alpha2, 3.0.0-alpha3, 3.x-dev].


Installation failed, reverting ./composer.json to its original content.

i can't get it work with neither --ignore-platform-reqs etc.

**Comment by wilr** [comment]
PR for this at #672.
