### ISSUE TITLE
SS42 Not Compatible Without Compser Change

### ISSUE THREAD

**Issue by gordonbanderson** [silvershop/silvershop-core#673]
hi,

I had to make the following change to get the shop compatible with SS42, https://github.com/silvershop/silvershop-core/commit/46fcc22741e77e068af608ee5bce785415cedc3a - perhaps it would be best not rely on recipes as a dependency?

Cheers

Gordon

**Comment by bummzack** [comment]
Duplicate of #671

**Comment by gordonbanderson** [comment]
Apologies, did not notice the dupe.  Coming back to programming after a 5 week break.  Code mode not quite on yet
