### ISSUE TITLE
Stepped checkout bug

### ISSUE THREAD

**Issue by liamchowneydev** [silvershop/silvershop-core#677]
I have silverstripe 4.2 and silvershop "silvershop/core": "dev-master as 3.0.0-alpha4", I originally had the willr patch but I was advised to change it to the above and everything has worked perfectly. I needed to change it because composer couldnt install modules like stock for example.

When I am going through stepped checkout I get this error.
[Notice] Use of undefined constant SHOP_DIR - assumed 'SHOP_DIR'

For the sake of debugging I harcoded the javascript path into address book to remove the top error and then I got this error
[User Notice] File vendor/silverstripe/framework/thirdparty/jquery/jquery.min.js does not exist

I then commented out the requirement for jquery because its included by default again for the sake of debugging.

I then get to the address checkout step. If I click the radio button "create new address" it works and allows me to continue. If the system finds an existing address it auto selects it, at that point when I continue I get this error
[Emergency] Uncaught TypeError: Argument 1 passed to SilverShop\Shipping\Model\Zone::cache_zone_ids() must be an instance of SilverShop\Model\Address, null given, called in /home/oneweigh/public_html/vendor/silvershop/shipping/src/Extension/OrderShippingExtension.php on line 98

**Comment by wilr** [comment]
Raised a PR (#678) for require issues.
