### ISSUE TITLE
Variation Image needs to be published when Saved

### ISSUE THREAD

**Issue by sparkcom** [silvershop/silvershop-core#684]
I have to write an extension to extent Variation class with the following:
` public function onBeforeWrite (){
            parent::onBeforeWrite();
            $img = $this->owner->Image();
            if($img ){
                $img->doPublish();
            }
        }`

I think the above should be in the class by default.

**Comment by bummzack** [comment]
This is covered by the `$owns` API. There was a bug in previous versions of SilverStripe 4 that required a workaround like you outlined.
With the latest Version of SS4 (4.2.1 as of this writing), the bug should be resolved.
