### ISSUE TITLE
Stepped Checkout not working

### ISSUE THREAD

**Issue by showtelllance** [silvershop/silvershop-core#689]
Hi, using the latest silvershop and silverstripe versions in tandum with the silvershop shipping module, the stepped checkout system simply isnt working. I have enabled the steps in the config and followed the guide on the shipping module however the checkout system just behaves as if there were no steps in place and acts exactly as I did before.

I have a similar shop done fairly recently that also runs on silverstripe 4.2.1 but an older version of the shop that does not have this issue so it feels like something that may have happened in the last couple of updates. Any ideas?

**Comment by wilr** [comment]
@showtelllance Perhaps try the SilverStripe Forums or Slack channel for debugging support and see if you get a particular error message. Can reopen a Issue if you can get more information.
