### ISSUE TITLE
CartPage and CheckoutPage records are created multiple times

### ISSUE THREAD

**Issue by marcokernler** [silvershop/silvershop-core#690]
Unless I set the 'create_default_pages' option for both page types to false, both records will be re-created on each /dev/build.

It seams `self::get()->exists()` in [CheckoutPage](https://github.com/silvershop/silvershop-core/blob/2cce31d6246e62a2831938dd831a1d67cb8f52d3/src/Page/CheckoutPage.php#L87) and [CartPage](https://github.com/silvershop/silvershop-core/blob/2cce31d6246e62a2831938dd831a1d67cb8f52d3/src/Page/CartPage.php#L79), returning false even if the specific page already exists.

I installed SilverStripe via the `"silverstripe/recipe-cms": "4.2.1@stable",` recipe.

**Comment by wilr** [comment]
@marcokernler You don't happen to subclass those pages in your project do you?

**Comment by marcokernler** [comment]
hi @wilr, nope - no subclassing. This happened after a fresh installation...

**Comment by sparkcom** [comment]
i remember i got the same problem, i put 

```
SilverShop\Page\CheckoutPage:
  create_default_pages: false
```

in my config.yml file
