### ISSUE TITLE
Cart form has ?Stage=Stage in action

### ISSUE THREAD

**Issue by sparkcom** [silvershop/silvershop-core#694]
When $Form shows in a published page, there is ?Stage=Stage attached to the form action url. for example:

<form id="CartForm_CartForm" action="/cart/CartForm/?stage=Stage" method="post" enctype="application/x-www-form-urlencoded">

The Form is a function defined in the page controller by the way.

This is causing problem because one has to login to the site in order to submit the form.

**Comment by wilr** [comment]
Is your page statically published or something? The ?Stage=Stage would only be included if you viewed the form on draft mode.

**Comment by sparkcom** [comment]
No it's not statically published. not sure what went wrong. 

Although i can use js to remove ?Stage=Stage, the link sent to payment gateway has ?Stage=Stage in it. So when user is redirected back, it redirect users back to /checkout/order/ID?Stage=Stage 

Only the Cart page and Checkout page has this problem. All other pages on the website are fine. 

Regards,

**Comment by wilr** [comment]
@sparkcom I would think you've got something forcing draft mode or updating your page's `Link()` action as I've tested on the demo site and a local install and cannot reproduce. If you can provide sample steps to reproduce on a clean project please reopen.
