### ISSUE TITLE
Change password in AccountPageController

### ISSUE THREAD

**Issue by sparkcom** [silvershop/silvershop-core#716]
Hello 

It looks like AccountPageController doesn't have the Action to handle the ChangePasswordForm 

If you click on 'Change password' you will have a 404 error.

**Comment by wilr** [comment]
`changepassword` should redirect users to the profile page https://github.com/silvershop/silvershop-core/blob/master/src/Page/AccountPageController.php#L250-L253. What version are you running @sparkcom

**Comment by sparkcom** [comment]
I am running "silvershop/core": "^3.0". @wilr . 

The form appears, but when you submit the form, there is 404 error.

**Comment by wernerkrauss** [comment]
I get 

>Could not find a suitable form-action callback function

in dev mode.

ChangePasswordForm looks for a method `doChangePassword` but doesn't find it.
