### ISSUE TITLE
Argument 1 passed to SilverStripe\Config\MergeStrategy\Priority::mergeArray() must be of the type array

### ISSUE THREAD

**Issue by vinstah** [silvershop/silvershop-core#723]
Hi,

I have just followed the setup guide (install SS, composer require silvershop/core) and copy the example-config.yml.

I get `Argument 1 passed to SilverStripe\Config\MergeStrategy\Priority::mergeArray() must be of the type array` when going to /admin after doing /dev/build?flush

If anyone else gets this issue this error is caused by `SilverShop\Reports\ShopPeriodReport:` in example-config.yml should be commented aswell

cheers

**Comment by wilr** [comment]
@vinstah could you submit a  PR with the required changes?

**Comment by wilr** [comment]
Fixed in #734
