### ISSUE TITLE
Uncaught BadMethodCallException: Object->__call(): the method 'TableTitle' does not exist on 'SilverShop\Model\Modifiers\Tax\FlatTax'

### ISSUE THREAD

**Issue by joshdillner** [silvershop/silvershop-core#731]
Looks like the function in Model/OrderAttribute.php has changed from "TableTitle" to "getTableTitle", but Model/Modifiers/Tax/Base.php still calls parent::TableTitle().

**Comment by joshdillner** [comment]
Cheers!

**Comment by joshdillner** [comment]
@wilr same issue on `SilverShop\Model\Modifiers\Shipping\Simple`.

**Comment by wilr** [comment]
Updated @joshdillner 👍

**Comment by joshdillner** [comment]
Cheers.
