### ISSUE TITLE
Sort Selectors not Translatable

### ISSUE THREAD

**Issue by gordonbanderson** [silvershop/silvershop-core#74]
The following code does not allow for i18n on the words 'Alphabetical' and 'Lowest Price'

      //TODO: allow grouping multiple sort fields under one 'sort option', and allow choosing direction of each
	protected static $sort_options = array(
		'URLSegment' => 'Alphabetical',
		'Price' => 'Lowest Price',
		//'NumberSold' => 'Most Popular'
		//'Featured' => 'Featured',
		//'Weight' => 'Weight'
	);

**Comment by bummzack** [comment]
Closed via #517
