### ISSUE TITLE
GridFieldOrderableRows on variations

### ISSUE THREAD

**Issue by intotheweb101** [silvershop/silvershop-core#745]
Hi I am wanting to add GridFieldOrderableRows to Variations on a Product, Code I have at the moment is 

`$gridField->getConfig()->addComponent($sort = new GridFieldOrderableRows('Sort'));`

Happy to make a pull request to add this in or if this is not something you want in the base just add a hook to update the cms fields

**Comment by wilr** [comment]
Yep feel free to add a PR to add the sortable behaviour and the sort field which I believe we don't have currently on the data object

**Comment by intotheweb101** [comment]
@wilr pull request logged #746
