### ISSUE TITLE
Incompatible with Silverstripe 4.6.0 (Versioned)

### ISSUE THREAD

**Issue by chromos33** [silvershop/silvershop-core#752]
There seems to be some changes in how Silverstripe 4.6.0 Versioned works.
It now "requires" an Silvershop_Variation_Live table which is not built. (don't know if this is a problem with Versioned or with how Variation deals with that). 
Just tell you in case there is something this module needs to change.

**Comment by Marimchen** [comment]
Hi @chromos33 , I cannot reproduce your issue. Over here it runs with 4.6.1 and Fluent 5 installed.

**Comment by chromos33** [comment]
Hey, uhm... can't remember anymore.
