### ISSUE TITLE
SS 4.7.2 installation problem

### ISSUE THREAD

**Issue by SlimoBanana** [silvershop/silvershop-core#759]
Hi please i have problem with installation.

composer.json
"require": {
        "php": "^7.1 || ^8",
        "silverstripe/recipe-plugin": "^1.2",
        "silverstripe/recipe-cms": "4.7.2@stable",
        "silverstripe-themes/simple": "~3.2.0",
        "silverstripe/login-forms": "4.3.0@stable",
        "silverstripe/googlesitemaps": "dev-master",
        "unclecheese/betterbuttons": "dev-master",
        "symbiote/silverstripe-gridfieldextensions": "dev-master",
        "colymba/gridfield-bulk-editing-tools": "^3.0",
        "undefinedoffset/sortablegridfield": "^2.0",
        "dorsetdigital/silverstripe-htmlminifier": "^1",
        "showpro/silverstripe-seo-images": "dev-master",
        "silvershop/core": "^3.0",
        "silverstripe/silverstripe-omnipay": "^3@dev"
    },
    
    After composer update site return
    
     Fatal error: Uncaught Symfony\Component\Yaml\Exception\ParseException: Duplicate key "GatewayRequestMessage" detected at line 30 (near "GatewayRequestMessage: SilverStripe\Omnipay\Model\Message\GatewayRequestMessage"). in /data/b/9/b96de0f7-0e3d-46d0-b7b7-609e4ca53570/site.com/sub/eshop/vendor/symfony/yaml/Parser.php:345 Stack trace: #0 /data/b/9/b96de0f7-0e3d-46d0-b7b7-609e4ca53570/site.com/sub/eshop/vendor/symfony/yaml/Parser.php(521): Symfony\Component\Yaml\Parser->doParse('SilverStripe\\Om...', 0) #1 /data/b/9/b96de0f7-0e3d-46d0-b7b7-609e4ca53570/site.com/sub/eshop/vendor/symfony/yaml/Parser.php(317): Symfony\Component\Yaml\Parser->parseBlock(3, 'Payment: Silver...', 0) #2 /data/b/9/b96de0f7-0e3d-46d0-b7b7-609e4ca53570/site.com/sub/eshop/vendor/symfony/yaml/Parser.php(521): Symfony\Component\Yaml\Parser->doParse('classname_value...', 0) #3 /data/b/9/b96de0f7-0e3d-46d0-b7b7-609e4ca53570/site.com/sub/eshop/vendor/symfony/yaml/Parser.php(317): Symfony\Component\Yaml\Parser->parseBlock(2, 'classname_value...', 0) #4 /data/b/9/b96de0f7-0e3d-46d0-b7b7-609e4ca53570/site.com/sub/eshop/vendor/symfony/yaml/Parser.php(95): Symfony\Component\Yaml\Parser->doParse('SilverStripe\\OR...', 0) #5 /data/b/9/b96de0f7-0e3d-46d0-b7b7-609e4ca53570/site.com/sub/eshop/vendor/symfony/yaml/Yaml.php(80): Symfony\Component\Yaml\Parser->parse('# Mapping rules...', 0) #6 /data/b/9/b96de0f7-0e3d-46d0-b7b7-609e4ca53570/site.com/sub/eshop/vendor/silverstripe/config/src/Transformer/YamlTransformer.php(204): Symfony\Component\Yaml\Yaml::parse('# Mapping rules...') #7 /data/b/9/b96de0f7-0e3d-46d0-b7b7-609e4ca53570/site.com/sub/eshop/vendor/silverstripe/config/src/Transformer/YamlTransformer.php(520): SilverStripe\Config\Transformer\YamlTransformer->getNamedYamlDocuments() #8 /data/b/9/b96de0f7-0e3d-46d0-b7b7-609e4ca53570/site.com/sub/eshop/vendor/silverstripe/config/src/Transformer/YamlTransformer.php(493): SilverStripe\Config\Transformer\YamlTransformer->filterByOnlyAndExcept() #9 /data/b/9/b96de0f7-0e3d-46d0-b7b7-609e4ca53570/site.com/sub/eshop/vendor/silverstripe/config/src/Transformer/YamlTransformer.php(103): SilverStripe\Config\Transformer\YamlTransformer->getSortedYamlDocuments() #10 /data/b/9/b96de0f7-0e3d-46d0-b7b7-609e4ca53570/site.com/sub/eshop/vendor/silverstripe/config/src/Collections/MemoryConfigCollection.php(73): SilverStripe\Config\Transformer\YamlTransformer->transform(Object(SilverStripe\Config\Collections\MemoryConfigCollection)) #11 /data/b/9/b96de0f7-0e3d-46d0-b7b7-609e4ca53570/site.com/sub/eshop/vendor/silverstripe/framework/src/Core/Config/CoreConfigFactory.php(91): SilverStripe\Config\Collections\MemoryConfigCollection->transform(Array) #12 /data/b/9/b96de0f7-0e3d-46d0-b7b7-609e4ca53570/site.com/sub/eshop/vendor/silverstripe/framework/src/Core/Config/CoreConfigFactory.php(67): SilverStripe\Core\Config\CoreConfigFactory->createCore() #13 [internal function]: SilverStripe\Core\Config\CoreConfigFactory->SilverStripe\Core\Config\{closure}() #14 /data/b/9/b96de0f7-0e3d-46d0-b7b7-609e4ca53570/site.com/sub/eshop/vendor/silverstripe/config/src/Collections/CachedConfigCollection.php(139): call_user_func(Object(Closure)) #15 /data/b/9/b96de0f7-0e3d-46d0-b7b7-609e4ca53570/site.com/sub/eshop/vendor/silverstripe/config/src/Collections/CachedConfigCollection.php(88): SilverStripe\Config\Collections\CachedConfigCollection->getCollection() #16 /data/b/9/b96de0f7-0e3d-46d0-b7b7-609e4ca53570/site.com/sub/eshop/vendor/silverstripe/framework/src/Core/Config/Config_ForClass.php(96): SilverStripe\Config\Collections\CachedConfigCollection->get('SilverStripe\\Co...', 'module_priority', 1) #17 /data/b/9/b96de0f7-0e3d-46d0-b7b7-609e4ca53570/site.com/sub/eshop/vendor/silverstripe/framework/src/Core/Config/Config_ForClass.php(129): SilverStripe\Core\Config\Config_ForClass->get('module_priority', 1) #18 /data/b/9/b96de0f7-0e3d-46d0-b7b7-609e4ca53570/site.com/sub/eshop/vendor/silverstripe/framework/src/Core/Manifest/ModuleManifest.php(232): SilverStripe\Core\Config\Config_ForClass->uninherited('module_priority') #19 /data/b/9/b96de0f7-0e3d-46d0-b7b7-609e4ca53570/site.com/sub/eshop/vendor/silverstripe/framework/src/Core/CoreKernel.php(533): SilverStripe\Core\Manifest\ModuleManifest->sort() #20 /data/b/9/b96de0f7-0e3d-46d0-b7b7-609e4ca53570/site.com/sub/eshop/vendor/silverstripe/framework/src/Core/CoreKernel.php(194): SilverStripe\Core\CoreKernel->bootManifests(false) #21 /data/b/9/b96de0f7-0e3d-46d0-b7b7-609e4ca53570/site.com/sub/eshop/vendor/silverstripe/framework/src/Control/HTTPApplication.php(135): SilverStripe\Core\CoreKernel->boot(false) #22 /data/b/9/b96de0f7-0e3d-46d0-b7b7-609e4ca53570/site.com/sub/eshop/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(65): SilverStripe\Control\HTTPApplication->SilverStripe\Control\{closure}(Object(SilverStripe\Control\HTTPRequest)) #23 /data/b/9/b96de0f7-0e3d-46d0-b7b7-609e4ca53570/site.com/sub/eshop/vendor/silverstripe/framework/src/Control/HTTPApplication.php(137): SilverStripe\Control\HTTPApplication->callMiddleware(Object(SilverStripe\Control\HTTPRequest), Object(Closure)) #24 /data/b/9/b96de0f7-0e3d-46d0-b7b7-609e4ca53570/site.com/sub/eshop/vendor/silverstripe/framework/src/Control/HTTPApplication.php(116): SilverStripe\Control\HTTPApplication->execute(Object(SilverStripe\Control\HTTPRequest), Object(Closure), false) #25 /data/b/9/b96de0f7-0e3d-46d0-b7b7-609e4ca53570/site.com/sub/eshop/public/index.php(24): SilverStripe\Control\HTTPApplication->handle(Object(SilverStripe\Control\HTTPRequest)) #26 {main} thrown in /data/b/9/b96de0f7-0e3d-46d0-b7b7-609e4ca53570/site.com/sub/eshop/vendor/symfony/yaml/Parser.php on line 345

Please what is wrong? Thank you so much.

**Comment by stnvh** [comment]
For now you'd need to use the older version of the yaml library used by SilverStripe, the new version is more strict with duplicate keys.

A temporary fix: 

`composer require symfony/yaml ^3`

**Comment by wilr** [comment]
Also I note the duplicate key is from the Omnipay library (https://github.com/silverstripe/silverstripe-omnipay/commit/762bc0276d2d9d61b64c1b9e5999c2a2bd8b6ebe)

**Comment by Noctis17** [comment]
Hello and good day! after installing the `composer require silvershop/core`, I had the same error, and searching deep made me come here. I tried issuing the `composer require symfony/yaml ^3` any solutions for this?

**Comment by wilr** [comment]
@Noctis17 make sure you're running a new version of Silverstripe to ensure the best compatibility.

**Comment by Noctis17** [comment]
Hello sir @wilr , yes sir, I've downloaded and installed the latest SilverStripe Framework, I've also raised this question in SilverStripe Slack 

https://app.slack.com/client/T0QSD6PRC/C0QSDASKT/thread/C0QSDASKT-1619405724.338800
