### ISSUE TITLE
Adding to Cart Issues

### ISSUE THREAD

**Issue by Snowboarder540** [silvershop/silvershop-core#760]
Hi Guys, 

On one of my websites (Silverstripe 3.7.3, Silvershop 2.2), we're getting an issue where the user is unable to add a product to their cart with certain browsers and devices.
This started happening in Firefox a while back when they introduced their New Advanced Tracking Protection Feature.  If this browser feature is deactivated "add to cart" works fine.  Unfortunately customers are now having similar issues with the latest iphones - I don't have one so I haven't been able to test.
Has this been an issue that has already been fixed in Silvershop ( I tried looking at the changelogs in github but couldn't find anything)?  Has anyone else experienced this and found a fix already?

I wanted to confirm this before I go through the process of trying to update the site.  

Thank you,

**Comment by wilr** [comment]
@Snowboarder540 As far as I am aware this works fine and we haven't noticed it on any sites of ours. To confirm your Firefox isn't set to block all cookies? To confirm you're running HTTPS, your cookie domain matches the website domain and your cookies are secure?

**Comment by Snowboarder540** [comment]
Thanks @wilr - your feedback regarding the cookie matching the domain helped me discover that the website was switching between urls at certain times (switching up between "www" or blank, as well as possibly http and https).  

Forcing a consistent url in .htaccess seems to have resolved the issue. 

Thank you,
