### ISSUE TITLE
Please opt-out of HTML5 processing of ISO 8601 dates via setHTML5(false) if using setDateFormat()

### ISSUE THREAD

**Issue by Anytech** [silvershop/silvershop-core#764]
All of the reports with dates are pulling up this error: 

```[Emergency] Uncaught LogicException: Please opt-out of HTML5 processing of ISO 8601 dates via setHTML5(false) if using setDateFormat()```

**Comment by kenlog** [comment]
Hi @Anytech I was passing :runner:  by and I take this opportunity to be useful to you and someone else, to use the HTML5 calendar you can use the `setValue ()` method

```php
DateField::create('Date')->setValue('YYYY-MM-DD')->setHTML5(true)
```

https://github.com/silverstripe/silverstripe-framework/blob/e63b73ad983f2ad402c5cdbfef4ba1e12461bc5b/src/Forms/DateField.php#L332

**Comment by 107p** [comment]
I am getting the same issue, but as a workaround added the following to config. Not sure if it would impact anything else though.

SilverShop\Reports\ShopPeriodReport:
  disable_set_date_format: false

**Comment by wilr** [comment]
Fixed in https://github.com/silvershop/silvershop-core/pull/815/files
