### ISSUE TITLE
website not forcing user to login

### ISSUE THREAD

**Issue by Thiyagarajantender** [silvershop/silvershop-core#778]
i am using silvershop for shopping page.

When i moving to check out (https://4es.os.mintdemo.co.nz/checkout) its not showing login adn registration form like demo https://demo.silvershop.io/checkout/.

Please advice.

**Comment by wilr** [comment]
@Thiyagarajantender Have you activated the membership step in your config? See https://github.com/silvershop/silvershop-demo/blob/master/app/_config/app.yml for the configuration for the demo.

**Comment by Thiyagarajantender** [comment]
I have updated like above and got  error.

ERROR [Emergency]: Uncaught InvalidArgumentException: Object::add_extension() - Can't find extension class for "SilverShop\Shipping\Checkout\Step\CheckoutStepShippingMethod" IN GET /4e-consulting/dev/build/?flush=all Line 186 in F:\xampp7\htdocs\4e-consulting\vendor\silverstripe\framework\src\Core\Extensible.php Source ====== 177: $class = get_called_class(); 178: $extension = $classOrExtension; 179: } 180: 181: if (!preg_match('/^([^(]*)/', $extension, $matches)) { 182: return false; 183: } 184: $extensionClass = $matches[1]; 185: if (!class_exists($extensionClass)) { * 186: throw new InvalidArgumentException(sprintf( 187: 'Object::add_extension() - Can\'t find extension class for "%s"', 188: $extensionClass 189: )); 190: } 191: 192: if (!is_subclass_of($extensionClass, Extension::class)) { Trace ===== SilverStripe\View\ViewableData::add_extension(SilverShop\Shipping\Checkout\Step\CheckoutStepShippingMethod) SteppedCheckoutExtension.php:63 SilverShop\Extension\SteppedCheckoutExtension::setupSteps(Array) _config.php:7 require_once(F:\xampp7\htdocs\4e-consulting\vendor\silvershop\core\_config.php) Module.php:422 SilverStripe\Core\Manifest\requireFile(F:\xampp7\htdocs\4e-consulting\vendor\silvershop\core/_config.php) Module.php:206 SilverStripe\Core\Manifest\Module->activate() ModuleManifest.php:154 SilverStripe\Core\Manifest\ModuleManifest->activateConfig() CoreKernel.php:213 SilverStripe\Core\CoreKernel->bootConfigs() CoreKernel.php:197 SilverStripe\Core\CoreKernel->boot(1) HTTPApplication.php:135 SilverStripe\Control\HTTPApplication->SilverStripe\Control\{closure}(SilverStripe\Control\HTTPRequest) HTTPMiddlewareAware.php:65 SilverStripe\Control\HTTPApplication->callMiddleware(SilverStripe\Control\HTTPRequest, Closure) HTTPApplication.php:137 SilverStripe\Control\HTTPApplication->execute(SilverStripe\Control\HTTPRequest, Closure, 1) HTTPApplication.php:116 SilverStripe\Control\HTTPApplication->handle(SilverStripe\Control\HTTPRequest) index.php:24

Please review my config .yml also

---
Name: app
After: silvershop/config#shopconfig
---
SilverStripe\Core\Manifest\ModuleManifest:
    project: 'app'
    
SilverShop\Checkout\CheckoutConfig:
  member_creation_enabled: true
  membership_required: true

SilverStripe\Control\Email\Email:
  admin_email: example@example.com

SilverStripe\i18n\i18n:
  default_locale: en_NZ

SilverShop\Model\Order:
  modifiers:
    - 'SilverShop\Model\Modifiers\Shipping\Simple'
    - 'SilverShop\Model\Modifiers\Tax\FlatTax'
  cancel_before_payment: false
  cancel_before_processing: false
  cancel_before_sending: false
  cancel_after_sending: false
  # Change / add order status, added Refunded
  db:
    Status: Enum('Unpaid,Paid,Processing,Refunded,Sent,Complete,AdminCancelled,MemberCancelled,Cart','Cart')
  # For logging order status changes & emailing notifications to customers
  log_status:
    - Processing
    - Sent
    - MemberCancelled
    - AdminCancelled

SilverShop\Page\CheckoutPage:
  steps:
    'membership': 'SilverShop\Checkout\Step\Membership'
    'contactdetails': 'SilverShop\Checkout\Step\ContactDetails'
    'shippingaddress': 'SilverShop\Checkout\Step\Address'
    'billingaddress': 'SilverShop\Checkout\Step\Address'
    'shippingmethod': 'SilverShop\Shipping\Checkout\Step\CheckoutStepShippingMethod'
    'paymentmethod': 'SilverShop\Checkout\Step\PaymentMethod'
    'summary': 'SilverShop\Checkout\Step\Summary'
    
SilverShop\Forms\OrderActionsForm:
  # allow_paying: false # disable prompt to pay an unpaid order on the AccountPage
  # allow_cancelling: true # allow cancelling of an order on the AccountPage
  email_notification: true  # Send email upon cancellation of an order
  allow_cancelling: true
  allow_paying: true

#SilverShop\Checkout\OrderProcessor:
#  send_confirmation: true  #send order confirmation when an order is placed, but unpaid
#  send_admin_notification: true  # copy to admin

SilverShop\Page\Product:
  # global_allow_purchase: false # prevents the purchase of any product and disables adding to cart
  # length_unit: 'M'
  # weight_unit: 'Pounds'
  db: # Revised decimal places
    BasePrice: 'Currency(19,2)'
    Weight: 'Decimal(12,3)'
    Height: 'Decimal(12,3)'
    Width: 'Decimal(12,3)'
    Depth: 'Decimal(12,3)'

# Change the dimensions of product thumbnails
SilverShop\Extension\ProductImageExtension:
  thumbnail_width: 140
  thumbnail_height: 100
  content_image_width: 200
  large_image_width: 200

SilverShop\Page\ProductCategory:
  include_child_groups: true
  must_have_price: true
  sort_options:
    'Title' : 'Alphabetical'
    'Price' : 'Lowest Price'

SilverShop\Extension\ShopConfigExtension:
  base_currency: 'NZD'
  email_from: sales@myshop.com

SilverShop\ORM\FieldType\ShopCurrency:
  decimal_delimiter: '.'
  thousand_delimiter: ','
  # european style currencies, e.g. 45,00 € instead of €45,00
  append_symbol: true

SilverShop\Cart\ShoppingCartController:
  # Redirect to the cart page after manipulating the shopping cart
  direct_to_cart_page: true
  # disable security token for cart-links
  disable_security_token: true

#SilverShop\Reports\ShopPeriodReport:
  # IF you are using the silverware/calendar module, uncomment the following line
  #disable_set_date_format: true

**Comment by wilr** [comment]
Error message is clear at the top `Can't find extension class for "SilverShop\Shipping\Checkout\Step\CheckoutStepShippingMethod` you probably don't have the Shipping module installed. If not, remove that from the config. Otherwise check that class exists and if you have done a ?flush=1
