### ISSUE TITLE
AddressBook  error 'File vendor/silverstripe/admin/thirdparty/jquery/jquery.js does not exist' after upgrade to SS 4.12.1

### ISSUE THREAD

**Issue by EEKimS** [silvershop/silvershop-core#781]
It appears that the original jquery file used by the AddressBook class no longer exists after the upgrade, causing the shipping details sections of the multipage checkout to throw errors.

`Requirements::javascript('silverstripe/admin:thirdparty/jquery/jquery.js');`
on line 37 of AddressBook.php

I am attempting to overload this class to change this address in my project - however, it would be nice to have this fixed for going forward without having to hack the core or manually overload it.

**Comment by xini** [comment]
Hey EEKimS,
We've been using https://github.com/xini/silverstripe-requirements-resolver to override any ancient jQuery versions loaded by other modules. Maybe it helps you here?
Cheers

**Comment by EEKimS** [comment]
Hi @xini,
That does seem to have done the trick, thank you very much!

**Comment by xini** [comment]
Can you please reopen this? I think it still needs fixing.

**Comment by BettinaMaria98** [comment]
Hi, something new here? We got this problem too...
CMS 4.12.0
SilverShop 3.0.4

**Comment by BettinaMaria98** [comment]
@xini thanks for pointing that out, we will do that!

**Comment by EEKimS** [comment]
Can confirm that the requirements resolver did not help with the issue, still getting the error - and it is proving to be very difficult to include my own in the correct file.

**Comment by wilr** [comment]
https://github.com/silvershop/silvershop-core/commit/d9d5d4bcc8bf0407ccc9cb4e31a4583b7a117fa8

**Comment by xini** [comment]
Thanks @wilr !

**Comment by wernerkrauss** [comment]
Nice solution @wilr
