### ISSUE TITLE
Github Actions for PHPUnit Tests

### ISSUE THREAD

**Issue by AntonyThorpe** [silvershop/silvershop-core#783]
I recommend dropping Travis and using Github Actions for PHPUnit Tests.  It is free, easy to use and the reports are good.  Here is some info: https://github.com/silverstripe/gha-ci.  If someone authorised is happy to set Github Actions up for PHPUnit tests, I will forward PRs to upgrade SilverShop's tests to PHPUnit 9.5.  There's a deal!

**Comment by wilr** [comment]
Yep sounds like a plan!

**Comment by AntonyThorpe** [comment]
Done.  Thanks.
