### ISSUE TITLE
Order Extension 'updateLink' does not work

### ISSUE THREAD

**Issue by EEKimS** [silvershop/silvershop-core#830]
I am using SilverStripe 4 at the moment, have not had a chance to update the client site to 5 yet. 

I have added an extension onto the Order class in an attempt to create a Thank You page instead of the Order Page, however, the `updateLink` function seems to be ignored.

```php
public function updateLink($link){
	$link = SilverShop\Page\CheckoutPage::find_link(false, 'thankyou');
	$link .= "?". http_build_query(['order' => $this->owner->ID]);		
}
```

The thank you page has been added to the checkout page controller and works correctly, however, the order processor completely ignores this and goes to the normal Order and Account Order Page.

I might be missing something obvious, but i don't see any other place that even uses this function that could be overriding it!

Please help

**Comment by wilr** [comment]
Does the argument need to be a reference? If you're not passing by reference and also not returning anything no changes to $link will be made. Try updateLink(&$link)

**Comment by EEKimS** [comment]
What would be better? Should i do a return, that didn't seem to have any effect either.

**Comment by wilr** [comment]
It depends on the callee whether it expected you do to it by reference or return. I don't have the code at hand to double check but you likely need to do it by reference.

**Comment by EEKimS** [comment]
it does appear that the `&$link` did the job, thank you, i was losing my mind on this.
