### ISSUE TITLE
Restrict payment methods

### ISSUE THREAD

**Issue by jedateach** [silvershop/silvershop-core#95]
Allow payment methods to only be used in specific regions, by specific groups, and within certain payment ranges etc.

A PaymentMethod class can be used to configure this.

Here are some examples that might help spell out the benefits:

 * Only allow bank-wire transfer in your own country
 * Restrict some payment types to admin group, for testing purposes, until ready for live usage.
 * Only allow secure payment methods  in untrusted countries
 * Special payment types for members

**Comment by wilr** [comment]
I think this is probably too specific for silvershop core and likely the realm of a module or custom code. Closing as there's plenty of work in the backlog.
